### ISSUE TITLE
Read directly from numpy 2d array, or a list of lists.

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#106]
Does this feature exist? Currently we have `read_csv`, `read_csv_file` and `read_pandas`. However `read_pandas` is not useful for testing since pandas is not a requirement. Instead, we should have `read_numpy_array` or `read_list` rather than worry about marshaling datasets back and forth to csv. 
List of lists is probably better than `numpy` since the latter is not a formal dependency 
(although any reasonable user will have it, since `crosscat` is a requirement).

**Comment by gregory-marton** [comment]
I think we can read from a dataframe now?
https://github.com/probcomp/bayeslite/blob/master/src/read_pandas.py
