### ISSUE TITLE
automatic tests for read_pandas

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#107]
Can mock up a pandas dataframe in order to avoid having to import pandas -- the API we rely on is probably pretty stable.

**Comment by gregory-marton** [comment]
https://github.com/probcomp/bayeslite/blob/master/tests/test_read_pandas.py

**Comment by riastradh-probcomp** [comment]
FYI, better to cite commits than URIs like that -- those URIs are not stable and do not refer to historical events.  In this case, the relevant commit is a4f9813da840ff7bc16295da538aac44c853b315.
