### ISSUE TITLE
guess IGNORE on large categoricals

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#113]
- ulimits?
- Specific limits on categoricals?
- ...?

**Comment by marcoct** [comment]
This is probably a digression, but it might be informative to think about the transformation to indicator variables, one for each possible category. This of course weakens the model by removing constraints, which could possibly be re-instantiated with some other enforcement mechanism, but I'm not sure how transformation would scale on the current implementation. I'm not suggesting this, but it may be relevant to keep in mind when addressing this issue.

**Comment by gregory-marton** [comment]
Let's separate the design discussions here from the task of actually guessing IGNORE on large categoricals, implement that asap, and then come back to what to do with specific interesting kinds of large categoricals (as described above) later?

The relevant code is in https://github.com/probcomp/bayeslite/blob/master/src/guess.py

**Comment by gregory-marton** [comment]
@raxraxraxraxrax, can you do some of the separation of thoughts here into a new document, a researchy question for after the analysis release.

**Comment by riastradh-probcomp** [comment]
I started a draft of this a couple months ago on the 20150919-riastradh-guesscatlimit branch:

https://github.com/probcomp/bayeslite/tree/20150919-riastradh-guesscatlimit

**Comment by gregory-marton** [comment]
Do you recall why it remains in an unresolved state? Did you get busy with other things, or was there a problem with the draft?

**Comment by vkmvkmvkmvkm** [comment]
We definitely want a "data transform" layer that automates standard
(re)encodings like this, by modifying the statistical types. E.g. instead
of "categorical" we might have a subtype "categorical via indicators" or
similar.
ᐧ

**Comment by riastradh-probcomp** [comment]
@gregory-marton: I don't remember why it remains unresolved.  I probably just got busy.  It probably doesn't have tests and the number 1000 pulled out of my arse could probably stand some more thought than I gave it.

**Comment by gregory-marton** [comment]
https://github.com/probcomp/bayeslite/commit/8b87fd10cbb7bbb85badbfb15e88ab470757aa81

I chose "large" to mean that above a given ratio is distinct. If there are 2000 categories, but also 10000 examples of each, then we may be able to clean quite a lot from it, and not fall down this way, right?
