### ISSUE TITLE
show probabilities in decibels

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#114]

**Comment by gregory-marton** [comment]
This would be useful not only in the shell, but perhaps as a formatter more generally.

**Comment by gregory-marton** [comment]
The issue at hand is the difficulty of seeing the important part of a probability in scientific notation. When you see 3.14159265358979323E-12, then most people's eyes don't immediately jump to the -12 part, which is the only part that matters for most probability interpretations. Something that puts that first, and limits the false precision might be useful.

**Comment by gregory-marton** [comment]
One option for this, if we're in ipynb land, is once again to create a chrome extension that formats scientific notation in a more readable way, emphasizing the correct part, e.g. using font sizes, and/or styles.

**Comment by riastradh-probcomp** [comment]
Doing this generally requires #38 and #41.

**Comment by riastradh-probcomp** [comment]
Hmm.  What I meant is actually #115, which transitively requires #38 and #41.

**Comment by fsaad** [comment]
Voting to close, in favor of #360.
