### ISSUE TITLE
Package for Anaconda with conda

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#117]
Documentation at http://conda.pydata.org/docs/building/bpp.html

Looks like we write a meta.yml and then build it somehow.

**Comment by tibbetts** [comment]
Tagged help wanted since it would be great to get an actual anaconda user to package and submit.

**Comment by tibbetts** [comment]
It now seems to be the case that pip install bdbcontrib works cleanly with Anaconda 2.4.1 and installs crosscat and bayeslite. That should reduce demand for a specialized package.

**Comment by gregory-marton** [comment]
Does it install bayeslite-apsw? Before I declare this done, I'd love to see a jenkins test that confirms that it installs correctly, runs the Satellites notebook, and passes tests, along the lines of the pip-install jenkins test.

**Comment by fsaad** [comment]
Related: https://github.com/probcomp/bayeslite/pull/582
