### ISSUE TITLE
Make guess and crosscat more clearly the default

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#119]
Also from conversation with @gregory-marton 

When creating a population, one should not have to explicitly ask for statistical type guessing or crosscat, it should just be the default model.

**Comment by raxraxraxraxrax** [comment]
This is a candidate for a future analysis release.

**Comment by riastradh-probcomp** [comment]
This sounds like a user interface issue, not an API issue in bayeslite.

**Comment by gregory-marton** [comment]
quickstart implements this silent default user interface.
