### ISSUE TITLE
design and implement foreign predictors

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#12]
Still not clear on what these are other than metamodels with only INITIALIZE/ANALYZE and PREDICT/SIMULATE, not MUTUAL INFORMATION or anything else like that.

Need some illustrative examples to generalize from.

**Comment by tibbetts** [comment]
This wants to come back to trunk post gpm refactor.

**Comment by fsaad** [comment]
@tibbetts the branch has been merged in `bdbcontrib`, should I close this issue and set a separate one for 'migrate foreign predictor to trunk'?

**Comment by tibbetts** [comment]
Just close this.
