### ISSUE TITLE
Crosscat insertmany broken?

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#123]
Taylor tells me that crosscat's implementation of insertmany is likely to be broken, as it does not interact with the crosscat subsample table.

**Comment by gregory-marton** [comment]
Duplicate of #30?

**Comment by riastradh-probcomp** [comment]
Not exactly -- this is about Crosscat's implementation of the `insertmany` API, whereas #30 is about (re)designing the API and/or using it to implement `INSERT` in BQL.

**Comment by fsaad** [comment]
The insert_many function no longer exists as of 5bf3d2d.

Ticket to implement this feature correctly is: https://github.com/probcomp/bayeslite/issues/493
