### ISSUE TITLE
OSX build should not prompt people to install git on launch.

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#139]
Something is probably running git, which will be in the path by default on osx and do this silly prompting.

**Comment by raxraxraxraxrax** [comment]
This is definitely still a problem, it happened to me today.

**Comment by raxraxraxraxrax** [comment]
I can reproduce this due to a quirk of OS X, I will keep this reproducible for now. :)

**Comment by raxraxraxraxrax** [comment]
![screen shot 2015-11-17 at 5 34 17 pm](https://cloud.githubusercontent.com/assets/6318314/11227017/852258f8-8d51-11e5-8046-df03d85ca8bb.png)

**Comment by riastradh-probcomp** [comment]
My first guess is that the VERSION file is broken or src/version.py is missing -- but that doesn't make sense, because the OS X .app should not involve the source tree or setup.py at all.

At this point I'd try dtrussing it.

**Comment by gregory-marton** [comment]
Ugh. dtruss no longer works on osx el capitan: http://internals.exposed/blog/dtrace-vs-sip.html

**Comment by gregory-marton** [comment]
Ipython/utils/sysinfo.py checks to see if it's being run in a git repo during sys_info, and the notebook app has sys_info calls in it. I think a general workaround might be the moral equivalent of 
ln -s /bin/echo $wd/venv/bin/git
in start.sh

@raxraxraxraxrax , might you be able to check that the above works (where $wd is perhaps ~/Desktop/Bayeslite-v0.1.3/Bayeslite-v0.1.3.app/Contents/MacOS
or wherever you have put a writeable copy)?

**Comment by riastradh-probcomp** [comment]
I suggest using ``which true`` instead of `/bin/echo`, since echo may be confused by hyphen options.

**Comment by riastradh-probcomp** [comment]
...no, that's no good either, if `true` is a shell built-in.

echo '#!/bin/sh' > $wd/venv/bin/git
chmod +x $wd/venv/bin/git

**Comment by gregory-marton** [comment]
@riastradh-probcomp, thanks for specifying the moral equivalent in question.

**Comment by raxraxraxraxrax** [comment]
Confirmed that @riastradh-probcomp 's workaround worked. I ran:

Macintosh-4:~ raxl$ echo '#!/bin/sh' > /Applications/Bayeslite-v0.1.3.app/Contents/MacOS/venv/bin/git
Macintosh-4:~ raxl$ chmod +x /Applications/Bayeslite-v0.1.3.app/Contents/MacOS/venv/bin/git

and then did not get the git error message.

**Comment by gregory-marton** [comment]
Thanks! I'll add this to the packaging.

**Comment by riastradh-probcomp** [comment]
Actually, a program that always fails might be better, so that callers will be less likely to parse the output upon seeing a nonzero exit status.  So perhaps something like this:

    printf '#!/bin/sh\nexit 1\n' > $wd/venv/bin/git
    chmod +x $wd/venv/bin/git

**Comment by riastradh-probcomp** [comment]
For the record, it looks like one can enable dtrace without disabling SIP altogether on OS X 10.11, according to <http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11> -- instead of running `csrutil disable` to disable SIP altogether, one can run `csrutil enable --without dtrace` to disable only restrictions on dtrace, when one is booted in 'recovery mode'.

**Comment by gregory-marton** [comment]
ab06a30

**Comment by gregory-marton** [comment]
This fails when the volume that bayeslite is on happens to be readonly, e.g. when we're running from the dmg. Make the dummy "git" program, but make it at packaging time, rather than on open.

**Comment by gregory-marton** [comment]
https://github.com/probcomp/packaging/commit/56f847374d01c0c187d0568b668f0f2c4b2d98d0
