### ISSUE TITLE
Using locate in packaging/osx/bayeslite/build_dmg.py is probably wrong

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#147]
We use locate to find libboost_atomic-mt.dylib, but (a) macs don't always have locate service running, there is a more mac friendly service mdfind, mdfind -name libboost_atomic-mt.dylib and more importantly (b) I don't think locate is required to respond with the best file, just a file with a matching name, so this could get weird on a machine with multiple boost installs.

Better to use whatever library resolution scheme crosscat is using, if we need boost.

**Comment by gregory-marton** [comment]
725e378
