### ISSUE TITLE
Ubuntu system iPython gives difficult to diagnose errors.

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#159]
@axch found this during bug disco.

> 1) IPython notebook doesn't open 2) import bayeslite from a fresh notebook seems to break looking for crosscat.  (2) is probably because I had an old crosscat installed by apt-get lying around. (1) is due to using stale system-wide IPython.

Solution might be a release note.

**Comment by raxraxraxraxrax** [comment]
Priority here depends on what our platform for users over IAP is. High if Ubuntu/Debian, low otherwise.

**Comment by gregory-marton** [comment]
I'm not sure what the release note should say. Perhaps something on the Ubuntu/Debian installation page, that you should update to python 2.7.9 or later, and that you should either install in a virtualenv (recommended) or ensure that you have `pip uninstall` -ed older versions of the software?

**Comment by fsaad** [comment]
Not experiencing this issue on recent build system.
