### ISSUE TITLE
OS X security settings block app launch

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#171]
Either settings need to be change to be permissive, or the user needs to right click and select open from the context menu in order to be offered the option to proceed.

Should be documented (R3) or we should learn to sign apps.

**Comment by raxraxraxraxrax** [comment]
https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html tells us what we need to do; do we already have a non-self-signed certificat kicking around somewhere for probcomp?

**Comment by gregory-marton** [comment]
I'm not aware of one. I think @riastradh-probcomp would have mentioned one when we were discussing distributions before.

**Comment by tibbetts** [comment]
I have an SSL cert for probcomp.org, so if that is helpful let me know.

I'm not sure if it is the right kind of widget for making Apple happy. In the past I thought that involved a paid apple developer account. But it may well have changed.

**Comment by riastradh-probcomp** [comment]
I have not generated an OS X code-signing key.

**Comment by fsaad** [comment]
The OS X release is no longer maintained.
