### ISSUE TITLE
Warning from iPython on syntax error backtrace

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#174]
q('''
    CREATE TEMP TABLE inferred_class AS
    INFER EXPLICIT
    anticipated_lifetime, perigee_km, period_minutes, type_of_orbit
    PREDICT class_of_orbit AS inferred_orbit_class
    CONFIDENCE inferred_orbit_class_conf
    FROM satellites_cc;''')

Got a lot of syntax errors. Missing comma before PREDICT got a warning from iPython saying:
```
>> ""ERROR: An unexpected error occurred while tokenizing input
>> The following traceback may be corrupted or invalid
>> The error message is: ('EOF in multi-line string', (1, 19))
```
before getting the whole backtrace as expected.

Are we producing something that iPython fails to escape and gets some error parsing a multiline string?

**Comment by gregory-marton** [comment]
I think first step is to work around this via #165, but we might also want to try to link this with an upstream bug in ipython, if we can produce a compact enough test case.

**Comment by riastradh-probcomp** [comment]
I'm not sure what error *bayeslite* reported here.  This issue should be focussed, I think, on the ipython bug about EOF in multi-line string while it tries to sprinkle angry fruit on the stack trace; we can make a separate issue (or append to #165) if bayeslite's own error report is confusing too.

**Comment by gregory-marton** [comment]
2448819 

<img width="1092" alt="screen shot 2016-02-06 at 6 01 23 am" src="https://cloud.githubusercontent.com/assets/5065456/12866305/dd36f64a-cc97-11e5-9840-831f01a3c30d.png">
