### ISSUE TITLE
Incorrect SIMULATE output

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#175]
@vkmvkmvkmvkm: 
    q('''
    SIMULATE country_of_operator, purpose FROM satellites_cc
    GIVEN country_of_operator = ""China (PR)"" 
    LIMIT 10;
    ''')
output incorrect --- non-chinese satellites generated. bayeslite bug most likely (not crosscat)

**Comment by riastradh-probcomp** [comment]
Fixed in Crosscat v0.1.29, crosscat#abc491c56be9ea639210c2b0c2aeec0aef4de372.
