### ISSUE TITLE
The nig_normal metamodel doesn't maintain the iteration count field of the model table

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#178]
Do we care about this?  Does that make it a poor example population model?

Issues:
- Counting iterations doesn't make sense for nig normal, because analysis always converges in one step
- Should there be a generic diagnostic/history saving feature?  Conversely, should counting the number of analysis iterations for crosscat be hidden inside crosscat's abstraction boundary?

**Comment by gregory-marton** [comment]
How does this bug manifest in terms of user experience?

**Comment by axch** [comment]
Well, right now most users wouldn't interact with non-crosscat metamodels at all.  If someone were to run the nig-normal metamodel (by source-diving and enabling BAYESDB_WIZARD_MODE), and queried the model metadata table for iteration counts to determine how much analysis some nig-normal models had undergone, they would be surprised by the answer.  Also, if someone were to study the code of the nig-normal metamodel in order to learn how to write their own metamodels, they would not learn about the model count updating mechanism.  That's all I can think of.

**Comment by gregory-marton** [comment]
Sounds like one solution is to add a note to this effect at the top of the nig_normal code, so that such a hypothetical user at least takes that into account? I'm not sure if having an open bug is actually helpful for that or a maintainer use case. What do you think?

**Comment by axch** [comment]
Note added in 8f01aca715effc04f54be3a27c558a544e7620f1.  You decide about the bug.

**Comment by gregory-marton** [comment]
Thanks!

**Comment by riastradh-probcomp** [comment]
Another alternative would be to transition from 0 to +\infty.
