### ISSUE TITLE
bayesdb_read_csv_file's ifnotexists is confusing

### ISSUE THREAD

**Issue by gregory-marton** [probcomp/bayeslite#183]
I thought that, by passing ifnotexists, I would be *reading* if not exists. Instead, it seems I was creating the table only ifnotexists.

Consider default behavior of doing nothing if the table is already present, having create default to True, and adding an append=False by default option?

**Comment by gregory-marton** [comment]
superseded by https://github.com/probcomp/bayeslite/issues/238

**Comment by riastradh-probcomp** [comment]
I don't understand how this is related to #238.  This is about loading data into an existing bdd; #238 opening a bdb in the first place.  Can you explain?

**Comment by gregory-marton** [comment]
I'm here taking "We could use the existence of the table as a proxy for the population of the data." to its logical conclusion, and effectively assuming that there is only one primary table of interest in a bdb for the purpose of analysis. Reading needs to be separated from opening only when that isn't true. When we do separate them, I think the two should still retain the same option format, and I find modes to be a less confusing option format than the current combination of booleans.

**Comment by leocasarsa** [comment]
The documentation is a bit confusing. What does "read data into it anyway" means? Overwriting? Appending? What?

```
    :param bool ifnotexists: if true, and `create` is true` and `table`
        exists, read data into it anyway
```

**Comment by fsaad** [comment]
I was confused about this function from the first day I read it sometime last year, and remain so until today.
