### ISSUE TITLE
Fixing variable overshadowing broke test_conditional_probability

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#192]
This pull request fixing overshadowing of a variable:
https://github.com/probcomp/bayeslite/pull/188

Broke the following test
    =================================== FAILURES ===================================
    _________________________ test_conditional_probability _________________________
    
        def test_conditional_probability():
            with test_core.t1() as (bdb, _generator_id):
                bdb.execute('initialize 1 model for t1_cc')
                bdb.execute('analyze t1_cc for 1 iteration wait')
                q0 = 'estimate probability of age = 8 by t1_cc'
                q1 = 'estimate probability of age = 8 given () by t1_cc'
                assert bdb.execute(q0).next()[0] == bdb.execute(q1).next()[0]
                q2 = 'estimate probability of age = 8 given (weight = 24) by t1_cc'
    >           assert bdb.execute(q0).next()[0] > bdb.execute(q2).next()[0]
    E           assert 0.02524238739795123 > 0.030745188129577952
    
    tests/test_bql.py:82: AssertionError
    ===Flaky Test Report===
    
    
    ===End Flaky Test Report===
    ======== 1 failed, 269 passed, 67 skipped, 17 xfailed in 169.99 seconds ========
    Build step 'Execute shell' marked build as failure
    Flowdock: Team Inbox notification sent successfully
    Finished: FAILURE

**Comment by tibbetts** [comment]
Test is passing.
