### ISSUE TITLE
bayeslite dependency on pexpect is missing from readme

### ISSUE THREAD

**Issue by marcoct** [probcomp/bayeslite#211]

**Comment by gregory-marton** [comment]
Perhaps the readme should refer people to setup.py for the up-to-date list of dependencies?

**Comment by riastradh-probcomp** [comment]
It should be put in setup.py tests_require.  I probably didn't notice
that it wasn't part of the standard CPython distribution.

**Comment by riastradh-probcomp** [comment]
Fixed in ca1029312431fd87cd5634a71537bdf2864aefd5.
