### ISSUE TITLE
setup.py doesn't run on Windows environment

### ISSUE THREAD

**Issue by jeroldhaas** [probcomp/bayeslite#212]
`setup.py` makes a call to `env` on line 120; Windows doesn't have env. Setup fails.

```
C:\Projects\Experiments\Python\bayeslite [master +3 ~0 -0 !]> C:\tools\python2\python.exe .\setup.py
generating src/grammar.y -> src/grammar.py
Traceback (most recent call last):
  File ".\setup.py", line 120, in <module>
    path_y,
  File "C:\tools\python2\lib\distutils\spawn.py", line 40, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\tools\python2\lib\distutils\spawn.py", line 79, in _spawn_nt
    "command %r failed: %s" % (cmd, exc[-1])
distutils.errors.DistutilsExecError: command '/usr/bin/env' failed: No such file or directory
```

**Comment by gregory-marton** [comment]
While we'd love to support building on Windows eventually, we don't currently have a windows test machine, nor anyone with special expertise in the subject. Would you be able to offer a patch?

**Comment by jeroldhaas** [comment]
As I'm not 100% familiar with python's libraries for platform detection, it may take me some time to hack something together.

I'll keep at it.

**Comment by gregory-marton** [comment]
Thank you!

**Comment by fsaad** [comment]
Windows users can use the Docker image at: https://github.com/probcomp/bayeslite/blob/master/docker/ubuntu1404
