### ISSUE TITLE
Overshadowing of "value" parameter by local variable in bqlfn

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#218]
Can you __believe__ that I fixed `colno` being overshadowed by changing `colno` to `col` in commit https://github.com/probcomp/bayeslite/commit/e6b67e939bddd2539ad6f9a6e0ce55750756fae8?
```
def bql_column_value_probability(bdb, generator_id, modelno, colno, **value**,
        *constraint_args):
    metamodel = core.bayesdb_generator_metamodel(bdb, generator_id)
    constraints = []
    i = 0
    while i < len(constraint_args):
        if i + 1 == len(constraint_args):
            raise ValueError('Odd constraint arguments: %s' %
                (constraint_args,))
        col = constraint_args[i]
----> value = constraint_args[i + 1]
        constraints.append((col, value))
        i += 2
    return metamodel.column_value_probability(bdb, generator_id, modelno,
        colno, value, constraints)
```

**Comment by riastradh-probcomp** [comment]
Date: Fri, 02 Oct 2015 16:24:09 -0700
   From: F Saad <notifications@github.com>

   Can you __believe__ that I fixed `colno` being overshadowed by changing `colno` to `col` in commit https://github.com/probcomp/bayeslite/commit/e6b67e939bddd2539ad6f9a6e0ce55750756fae8?

I've done things like that before too!

           col = constraint_args[i]
     ----> value = constraint_args[i + 1]
           constraints.append((col, value))

Maybe we ought to call the local variables `constraint_colno' and
`constraint_value'.

**Comment by axch** [comment]
This is all because Python confuses binding with assignment.  Guido, WTF?

Anyway, other solutions:
- make those variables actually local by pulling the while loop out into a function named `plist_to_alist`
- get rid of those not-local-enough variables entirely by inlining them into their unique use sites
