### ISSUE TITLE
Undocumented BQL query MUTUAL INFORMATION USING N SAMPLES?

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#219]
The query `ESTIMATE MUTUAL INFORMATION OF <X> WITH <Y> USING N SAMPLES FROM <foo>` seems to work  correctly, but this behavior is not documented in the [reference manual](http://probcomp.csail.mit.edu/bayesdb/doc/bql.html).

**Comment by riastradh-probcomp** [comment]
Date: Sun, 04 Oct 2015 13:25:44 -0700
   From: F Saad <notifications@github.com>

   The query `ESTIMATE MUTUAL INFORMATION OF <X> WITH <Y> USING N SAMPLES FROM <foo>` seems to work  correctly, but this behavior is not documented in the [reference manual](http://probcomp.csail.mit.edu/bayesdb/doc/bql.html).

Should be easy enough to fix, although I'm not sure this is the right
linguistic construct in the long run.  Need to think further about it
and about other similar cases.

**Comment by riastradh-probcomp** [comment]
Fixed in 43ae21761f4fd701ed1871054bc8050e6bc8b26f.
