### ISSUE TITLE
Buggy dependence probability equation in satellites ipynb

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#233]
`$Pr[ A dep B ] = Pr[ I( A ; B ) > 0 ] = \sum_i G_i w_i Pr[ I( A ; B ) > 0 | G_i ]`

should be

`$Pr[ A \perp B ] = Pr[ I( A ; B ) = 0 ] = \sum_i m_i INDICATOR[ I( A ; B ) = 0 | G_i ]`

**Comment by luac** [comment]
Shouldn't it be not `\perp`? Also, use `$$` to make the notebook render it with MathJax.

**Comment by marcoct** [comment]
I believe $A \perp G \iff I( A ; B ) > 0$. Using $\perp$ might be more interpretable by users.

**Comment by luac** [comment]
Oh huh. I hadn't seen that notation before.

**Comment by fsaad** [comment]
Anthony you are right -- I changed > 0 to =0, rather than do `not \perp`.

**Comment by gregory-marton** [comment]
@fsaad, is this fixed at HEAD?

**Comment by fsaad** [comment]
Satellites notebook is no longer maintained.
