### ISSUE TITLE
SIMULATE does not support GIVEN < and > predicates

### ISSUE THREAD

**Issue by marcoct** [probcomp/bayeslite#234]
simulate apogee_km, perigee_km from satellites_cc given apogee_km < 50000 limit 1000
BQLParseError: Parse error: syntax error near <

This is more of a feature request. I tried this conditional query before I tried apogee_km = 40000 as it seemed more natural given the context---I wanted to view the learned joint distribution of two variables within a given range to make more efficient use of samples.

Also, I'm guessing crosscat does not support this?

**Comment by fsaad** [comment]
related https://github.com/probcomp/bdbcontrib/issues/32

**Comment by fsaad** [comment]
> Also, I'm guessing crosscat does not support this?

There exists `get_predictive_cdf` in `ContinuousComponentModel` that is not used anywhere in the crosscat pipeline, and it is not exposed through the famous `sample_utils` (the query) interface.

**Comment by fsaad** [comment]
For arbitrary predicates, rejection sampling is required by simulating followed by filtering using `WHERE`.
