### ISSUE TITLE
Proposal: Implement naive Bayes as an alternative to Crosscat

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#236]
Benefits:
- Easy for a certain class of user to connect: "yes, this is what I would expect naive Bayes to do on this data
- Something for us to compare crosscat's inference quality performance against: for us, and for those users
- Right now, we keep comparing crosscat only to imaginary improved crosscat, causing us to itch to improve crosscat; implementing a baseline baseline may let us focus better on the rest of the system, treating crosscat as a baseline model among, conceptually, many.
- Exercise the GPM interface and generic tools written against it: testers, the composer, etc.

**Comment by fsaad** [comment]
Using MML and implement nothing new?
`ENSURE PAIRWISE INDEPENDENT`

**Comment by axch** [comment]
Sure, that could be a pretty easy way to draft it.  The pedagoical value is different, but that's ok.  I'm envisioning a metamodel that inherits from the crosscat metamodel, overrides create generator to add ensure independent statements, and is usable as
```
create generator frob for monkey using naive_bayes(column types or guess) -- no ensure commands here
```
I would want to aggressively quality test either version and confirm that it actually is naive Bayes.

Possible item: would a custom implementation be significantly faster than ensure independent?

**Comment by marcoct** [comment]
Having the same for finite mixture or for DPMM might be nice as well. Although its possibly harder to test with the same precision as naive Bayes, the similarity estimate is commonly understood in this case, and it would be a nice intermediate baseline between NB and CC.
```
create generator frob for monkey using mixture_infinite(column types or guess)
create generator frob for monkey using mixture_finite(column types or guess, k)
```

**Comment by luac** [comment]
A difference with the "ensure independent" implementation is that each column is then modeled by a mixture of component models, rather than a single component model (as is I think described in the paper). This is a significant modeling difference for component distributions other than categorical (mixture of gaussian/poisson/etc vs single mode), and a significant speed difference in that one of them has latent clusters to infer and the other one does not. I'm not sure which one this is supposed to be.

**Comment by fsaad** [comment]
These variants are now possible using the MML alteration syntax, see comment: https://github.com/probcomp/bayeslite/issues/571#issuecomment-344082357
