### ISSUE TITLE
Session warning fails when previous session has error

### ISSUE THREAD

**Issue by marcoct** [probcomp/bayeslite#237]
These two lines in src/sessions.py need to be fixed, and therefore these lines need to be switched:

```
        self._start_new_session()
        self._logger = logger
```

**Comment by marcoct** [comment]
The bug was fixed here:
https://github.com/probcomp/bayeslite/commit/56ccfc5791b0021e0207f1b1675640a53b17c4ba
but I will leave this ticket open until the unit test has been augmented to test for this. It will need to test the case where the previous session failed (currently it only tests if the current sessions has failures).

See tests/test_sessions.py

**Comment by gregory-marton** [comment]
Not needed for any release soon, because we will primarily use the recipes-based session capture instead.

**Comment by fsaad** [comment]
sessions.py wiped as of db1437f
