### ISSUE TITLE
Update copyright headers to include 2015

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#245]
Ditto crosscat and bdbcontrib
- crosscat's headers have somewhat stale author/maintainer information

On @riastradh-probcomp 's request, have not been doing that on a per-file basis, preferring to keep all the headers identical so they can be easily updated in one swell foop.

I wrote a script for Venture that queries git for actual modification dates and constructs headers with accurate year lists.  To be used here, it would need to be adapted/configured somewhat.

**Comment by gregory-marton** [comment]
Fixed by dc85ce1c2d6610e27b0fa89383d8bdb64b862f67 ? @raxraxraxraxrax , please verify?

**Comment by raxraxraxraxrax** [comment]
Confirmed in 0.1.4a build.
