### ISSUE TITLE
Create tables directly from Pandas dataframes

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#247]
Seems kinda silly to have read_csv and read_csv_from_file but not a from_df, since, as far as I can tell, dataframes are at least becoming and may already be the Python community's standard in-memory data interchange format.  In particular, Pandas provides its own highly articulated from_csv and to_csv conversions; and a dataframe retains all the information in the csv file (i.e. column headers).

Another potentially nice convenience (for MML users) would be to build a complete one-table database from a csv or a dataframe in one API call.

**Comment by tibbetts** [comment]
read_pandas_df exists and I'm using it with gapminder quite a lot.
https://github.com/probcomp/bayeslite/blob/master/src/read_pandas.py

**Comment by axch** [comment]
The "other potentially nice convenience" now exists as https://github.com/probcomp/bdbcontrib/blob/master/src/bql_utils.py#L128-L144 .  Do we want to migrate that to Bayeslite from bdbcontrib?

**Comment by tibbetts** [comment]
My bias was actually to move read pandas to bdbcontrib with other such functions since it isn't core.

**Comment by axch** [comment]
Also acceptable.
