### ISSUE TITLE
What semantics do we want for self mutual information?

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#251]
For example, the test query in #240 :

```
ESTIMATE MUTUAL INFORMATION OF Country_of_Contractor WITH Country_of_Contractor
FROM satelites_cc
LIMIT 1;
```

Possible interpretations:
- The mutual information of the predictive distribution for `Country_of_Contractor` on a fresh row, with itself (i.e., the two random variables whose MI is to be computed are always equal, and are  marginally distributed according to the predictive).
  - In the discrete case, this is the entropy of said predictive distribution, which we can compute (faster than the current thing by a factor of the number of values in the category).
  - In the continuous case, I don't know what this would mean, because the joint density is zero Lebesgue-almost everywhere; one option would be to just define it as the differential entropy of the column for (sort of) uniformity with the discrete case.
- The mutual information of two independent draws from the predictive on a fresh row
  - This is always zero
  - Is it also non-uniform with the meaning of MI of different columns
- The mutual information of those two cells drawn from the joint predictive on two fresh rows
  - This is again non-uniform with the meaning of MI of different columns
  - This is mildly non-zero, because the first draw will affect the shape of the cluster it gets assigned to, slightly nudging the second, but I don't know whether this quantity is interesting
- The mutual information of those two cells drawn from the joint predictive on two fresh rows that are _forced similar wrt this column_ (i.e., same unknown cluster)
  - This definition sounds pretty weird
  - This is what the current code actually computes

If we implement #250 , that is likely to automatically generate a mechanism for the user to choose between the first and third interpretation above.

**Comment by gregory-marton** [comment]
The entropy interpretation seems immediately useful in deciding something about precision or robustness of the model for that column. Is that a mistake? Sounds useful as part of analysis_status()!

**Comment by riastradh-probcomp** [comment]
I think the differential entropy is a more generally useful concept than any of the other alternatives you listed, and is a reasonable abuse of language.

**Comment by fsaad** [comment]
Behavior is to define self mutual-information as entropy.
