### ISSUE TITLE
Bayeslite explodes on large dataset

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#253]
800 row by 1900 column

```
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/bayeslite/txn.py", line 40, in bayesdb_savepoint
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/bayeslite/sqlite3_util.py", line 60, in sqlite3_savepoint
sqlite3.OperationalError: no such savepoint: xb9f3d212c1f9f5265af1ca3eedef434e7ecb858687971130c3e6ef44583f9943
```

 I ran using `screen` so full stack trace not available right now, but the issue is easily reproducible.

Here is another error that was thrown (same setup, more output)

```
fsaad@probcomp-1:~/surf-hist$ ipython -i surf_trainer.py
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
READING CSV
CREATING GENERATOR
INITIALINING MODELS
ANALYZING MODELS
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
/afs/csail.mit.edu/u/f/fsaad/surf-hist/surf_trainer.py in <module>()

/usr/local/lib/python2.7/dist-packages/bayeslite-0.1.post60_g1043957-py2.7.egg/bayeslite/bayesdb.pyc in execute(self, string, bindings)
    156         else:
    157             raise ValueError('>1 phrase in string')
--> 158         cursor = bql.execute_phrase(self, phrase, bindings)
    159         return self.empty_cursor if cursor is None else cursor
    160

/usr/local/lib/python2.7/dist-packages/bayeslite-0.1.post60_g1043957-py2.7.egg/bayeslite/bql.pyc in execute_phrase(bdb, phrase, bindings)
    456             max_seconds=phrase.seconds,
    457             ckpt_iterations=phrase.ckpt_iterations,
--> 458             ckpt_seconds=phrase.ckpt_seconds)
    459         return empty_cursor(bdb)
    460

/usr/local/lib/python2.7/dist-packages/bayeslite-0.1.post60_g1043957-py2.7.egg/bayeslite/metamodels/crosscat.pyc in analyze_models(self, bdb, generator_id, modelnos, iterations, max_seconds, ckpt_iterations, ckpt_seconds)
    982                         'generator_id': generator_id,
    983                         'modelno': modelno,
--> 984                         'iterations': iterations_done,
    985                     })
    986                     assert bdb.sqlite3.total_changes - total_changes == 1

/usr/local/lib/python2.7/dist-packages/bayeslite-0.1.post60_g1043957-py2.7.egg/bayeslite/bayesdb.pyc in sql_execute(self, string, bindings)
    174         if self.sql_tracer:
    175             self.sql_tracer(string, bindings)
--> 176         return bql.BayesDBCursor(self, self.sqlite3.execute(string, bindings))
    177
    178     @contextlib.contextmanager

OperationalError: unable to open database file

In [1]: bayeslite
Out[1]: <module 'bayeslite' from '/usr/local/lib/python2.7/dist-packages/bayeslite-0.1.post60_g1043957-py2.7.egg/bayeslite/__init__.pyc'>

In [2]: The history saving thread hit an unexpected error (OperationalError('disk I/O error',)).History will not be written to the database.
```

**Comment by riastradh-probcomp** [comment]
Date: Fri, 09 Oct 2015 17:07:47 -0700
   From: F Saad <notifications@github.com>

   sqlite3.OperationalError: no such savepoint: xb9f3d212c1f9f5265af1ca3eedef434e7ecb858687971130c3e6ef44583f9943

Weird.  Can't imagine how that could happen!

    I ran using `screen` so full stack trace not available right now, but the issue is easily reproducible.

FYI, screen has a small scrollback buffer, which you can get at with
`C-a [' and then use C-b/C-f to go backward/forward in it, or q to
exit.  (Can be expanded beforehand with, e.g., `C-a : scrollback
65536' to make it 64k lines long, or similarly in your .screenrc
file.)

**Comment by fsaad** [comment]
Here is another issue just encountered (subsampling 5000 rows, 200 cols)

```
fsaad@probcomp-1:~$ bayeslite/shell/scripts/bayeslite surf.bdb -j12
Welcome to the Bayeslite 0.1.post60+g1043957 shell.
Type `.help' for help.
bayeslite> analyze surf_cc for 50 iteration wait;
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/bayeslite/shell/core.py", line 133, in default
    cursor = bql.execute_phrase(self._bdb, phrase)
  File "build/bdist.linux-x86_64/egg/bayeslite/bql.py", line 458, in execute_phrase
    ckpt_seconds=phrase.ckpt_seconds)
  File "build/bdist.linux-x86_64/egg/bayeslite/metamodels/crosscat.py", line 984, in analyze_models
    'iterations': iterations_done,
  File "build/bdist.linux-x86_64/egg/bayeslite/bayesdb.py", line 176, in sql_execute
    return bql.BayesDBCursor(self, self.sqlite3.execute(string, bindings))
OperationalError: unable to open database file
```

**Comment by fsaad** [comment]
It seems that bayeslite is the problem here, not crosscat. Might have to analyze separately outside of bayeslite and bring in the JSON blob to run BQL.

**Comment by fsaad** [comment]
```
fsaad@probcomp-1:~$ bayeslite/shell/scripts/bayeslite sift.bdb -j32
Welcome to the Bayeslite 0.1.post60+g1043957 shell.
Type `.help' for help.
bayeslite> .read sift.bql
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/bayeslite/shell/core.py", line 133, in default
    cursor = bql.execute_phrase(self._bdb, phrase)
  File "build/bdist.linux-x86_64/egg/bayeslite/bql.py", line 317, in execute_phrase
    instantiate)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/bayeslite/bayesdb.py", line 186, in savepoint
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/bayeslite/txn.py", line 40, in bayesdb_savepoint
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/bayeslite/sqlite3_util.py", line 60, in sqlite3_savepoint
    db.execute("ROLLBACK TO x%s" % (savepoint,))
OperationalError: no such savepoint: x4ebee1adfbdf696e1e088ac5baa1506b56b9c9375fe74f44d2446c41b53d36cf
```
The files that generated this are located at
http://people.csail.mit.edu/fsaad/sift.bql
http://people.csail.mit.edu/fsaad/sift.bdb
http://people.csail.mit.edu/fsaad/sift_train.csv

**Comment by gregory-marton** [comment]
Any progress on this?

**Comment by riastradh-probcomp** [comment]
I have not yet taken a closer look at it.

**Comment by riastradh-probcomp** [comment]
I tried initializing 100 models.  The system ran out of memory and oom-killed python.

**Comment by riastradh-probcomp** [comment]
Another possibility which did not get recorded earlier: this may have been a matter of Kerberos/AFS tickets expiring and causing disk I/O from the bayeslite process to fail.

**Comment by riastradh-probcomp** [comment]
The average size of the per-model theta_json blobs is 11 MB.  That's pretty big: for 100 models that would require >1 GB of working memory just to represent the json blobs, let alone any of the copies in different (Python list/dict or C++ STL vector/map) formats we use.

There are on average 22 views per model and 2146 categories per view.  Most of the space (9 MB per model) is occupied by the per-category column sufficient statistics.

To avoid representing this all at once in memory, we would have to tighten the coupling between the C++ code and the Python/sqlite3 code so that the C++ code could conceivably work incrementally over a stream of results from a sqlite3 query, with all Crosscat data stored relationally, not as json blobs, in order for that to work.

A perhaps simpler approach would be to use a dense array rather than sparse dict representation in json.  But while that's likely to win with many binary features as you seem to have, it may not win with other data sets.

Another simpler approach would be to at least iterate over the models separately, rather than asking Crosscat to simultaneously do work in all models in memory at once before returning updates to the database -- but again, while that is likely to be a win here, it also increases the number of Python/C++ data conversion round-trips.  So it might be a win always, but I'm not totally sure of that.

**Comment by fsaad** [comment]
> Another possibility which did not get recorded earlier: this may have been a matter of Kerberos/AFS tickets expiring and causing disk I/O from the bayeslite process to fail.

I believe this indeed was the case at the time.
