### ISSUE TITLE
Bayeslite analysis does not terminate after specified time

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#255]
I ran a `bql` script with anlaysis for 600 minutes (10 hours) at the following time

```
39765.pts-5.probcomp-1  (10/13/2015 04:47:43 PM)    (Detached)
```

As of writing (10/14/2015 09:58:43 AM) the bayeslite terminal has not returned from the command

```
fsaad@probcomp-1:~$ bayeslite/shell/scripts/bayeslite maled.bdb
Welcome to the Bayeslite 0.1.post60+g1043957 shell.
Type `.help' for help.
bayeslite> .read maled.bql
...
```

The datastet and bql file can be found at `probcomp1:/scratch/fsaad` named `maled.bql` and `micro_x24.csv`.

**Comment by riastradh-probcomp** [comment]
If you open maled.bdb in another bayeslite shell, and run `.describe models micro_cc`, what does it say?

**Comment by fsaad** [comment]
```
fsaad@probcomp-1:~$ bayeslite/shell/scripts/bayeslite maled.bdb
.describe models micro_ccWelcome to the Bayeslite 0.1.post60+g1043957 shell.
Type `.help' for help.
bayeslite> .describe models micro_cc
modelno | iterations
--------+-----------
      0 |          0
      1 |          0
      2 |          0
      3 |          0
      4 |          0
      5 |          0
      6 |          0
      7 |          0
      8 |          0
      9 |          0
     10 |          0
     11 |          0
     12 |          0
     13 |          0
     14 |          0
     15 |          0
     16 |          0
     17 |          0
     18 |          0
     19 |          0
     20 |          0
     21 |          0
     22 |          0
     23 |          0
     24 |          0
     25 |          0
     26 |          0
     27 |          0
     28 |          0
     29 |          0
     30 |          0
     31 |          0
     32 |          0
     33 |          0
     34 |          0
     35 |          0
     36 |          0
     37 |          0
     38 |          0
     39 |          0
     40 |          0
     41 |          0
     42 |          0
     43 |          0
     44 |          0
     45 |          0
     46 |          0
     47 |          0
     48 |          0
     49 |          0
     50 |          0
     51 |          0
     52 |          0
     53 |          0
     54 |          0
     55 |          0
     56 |          0
     57 |          0
     58 |          0
     59 |          0
     60 |          0
     61 |          0
     62 |          0
     63 |          0
```

**Comment by riastradh-probcomp** [comment]
Right -- no checkpoints.  Bleh.  Can you do it again, but this time add something like `CHECKPOINT 1 MINUTE`?

**Comment by fsaad** [comment]
Will do.

Side question: do we need to checkpoint to get the number of iterations? I tried `analyze` on another small dataset, and the number of iterations appear non-zero (although after analysis has terminated).

**Comment by riastradh-probcomp** [comment]
I see -- I probably broke this last night.

**Comment by riastradh-probcomp** [comment]
You need to checkpoint in order to get the number of iterations -- or anything -- before the analysis has completed.

**Comment by riastradh-probcomp** [comment]
What I thought I might have broken last night is not obviously broken, so disregard that.

**Comment by gregory-marton** [comment]
I've experienced this. At the very least, it seems like if you do set a checkpoint, then it has to get to the next checkpoint before it looks to see if the requested time has elapsed.

**Comment by gregory-marton** [comment]
Ah, my experience has already been noted in #256

**Comment by riastradh-probcomp** [comment]
It is possible we could use a SIGALRM timer to interrupt analysis by setting a flag that every step of analysis, all the way down in C++ code, checks before it decides to proceed.

Difficulties:

- Unsure of the portability of timer interrupts in Python.
- Unsure of the composability of timer interrupts in Python.
- Needs useful cooperation between Python and C++ and signal handlers.

**Comment by fsaad** [comment]
I believe that this code path is no longer being maintained directly (CrosscatMetamodel), and the timeout code in code in crosscat has been rewritten.
