### ISSUE TITLE
INFER EXPLICIT and ESTIMATE have overlapping functionality

### ISSUE THREAD

**Issue by marcoct** [probcomp/bayeslite#264]
In trying to learn BQL myself, I am having a hard time building a simple mental model of why the top-level queries "ESTIMATE", "INFER EXPLICIT", "INFER", and "SIMULATE" have been factored as they are.

In particular, INFER EXPLICIT and ESTIMATE have overlapping functionality in that they both support model estimators of a single row:
```
infer explicit predictive probability of Purpose from satellites_cc
estimate predictive probability of Purpose from satellites_cc
estimate Name, similarity to (Name = "AAUSat-3") as sim FROM satellites_cc
infer explicit Name, similarity to (Name = "AAUSat-3") as sim FROM satellites_cc
```
This somewhat explains my failure so far to map the words "infer" and "estimate" to distinct meanings in BQL.

For example, it seems that "INFER EXPLICIT" supports a super-set of those column expressions that "ESTIMATE FROM (ROWS OF)" does. The documentation for "ESTIMATE FROM (ROWS OF)" states:
```
Like SELECT on the table associated with generator,
extended with model estimators of one implied row.
```
and the documentation for "INFER EXPLICIT" states:
```
Like SELECT on the table associated with generator,
extended with model estimators of one implied row and with model predictions.
```

**Comment by riastradh-probcomp** [comment]
We discussed this in person.  The quick summary is:

- SELECT simply computes a function of a table subset row-by-row.
- ESTIMATE computes a Monte Carlo average of a function of a model and a table row-by-row, averaged over all the models.
- The function PREDICT is not like what you can use in ESTIMATE -- it is a more complex summary of the posterior predictive distribution averaged over all the models.
- INFER and INFER EXPLICIT let you compute Monte Carlo averages over all the models *and* complex summarizing of the posterior predictive distribution.
