### ISSUE TITLE
Define column mutual information

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#269]
- Define it probabilistically
- Implement the definition as an (approximate?) algorithm against joint simulation and assessment
- Compare speed and quality against the structural implementation in crosscat

**Comment by gregory-marton** [comment]
Ditto. Does this mean extend to any logpdf_joint?

**Comment by axch** [comment]
We have a stronger probabilistic definition of this than of dependence probability, at least for just one model.  (I don't know offhand whether the average of MI across models constitutes an estimate of the marginal MI integrating out model uncertainty.  Probably does.)  I guess one thing I meant by "define" was "publically and evidently specify the probabilistic definition of this, notably in an appropriate segment of the documentation."

Implementing it generically would mean that any metamodel with a logpdf_joint (and simulate, as needed) would automatically have an estimate for this quantity.  (Presumably, the estimate provided by Crosscat would be substantially faster.)

**Comment by fsaad** [comment]
arxiv.org/abs/1611.01708
244af1972043b9034d2f5dbc4c83ee199802baff
