### ISSUE TITLE
Create a conventions document

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#273]
The software conventions of bayeslite should be outlined in a `README` document for new contributors to adhere to -- otherwise the code may become too standardized which impede readability.

For example we do not adhere to [PEP8 indentation](https://www.python.org/dev/peps/pep-0008/#indentation), to which @riastradh-probcomp says

> I chose to break with PEP8 for all code in bayeslite concerning continuation lines: four extra spaces per extra level, instead of alignment. That way, e.g., renaming a function doesn't usually change the indentation of the continuation lines, and a descriptive function name does not waste half the screen width.

> I also broke with PEP8 by omitting needless extra blank lines between top-level definitions: PEP8 says there should be two blank lines; I use one. I find the extra blank lines distracting.

These design decisions (and others) should be in a visible place (currently in commit message comments, etc).

**Comment by fsaad** [comment]
Exists in [HACKING](https://github.com/probcomp/bayeslite/blob/master/HACKING), should we close?

**Comment by riastradh-probcomp** [comment]
This is indeed what the HACKING file is for.

**Comment by fsaad** [comment]
OK, the name HACKING is a strange convention for a CONVENTION document.

**Comment by riastradh-probcomp** [comment]
HACKING is the document you read if you are going to do any hacking on bayeslite.
