### ISSUE TITLE
Fresh row ids for generic generators should be unique on every invocation

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#274]
Currently the function [`bayesdb_generator_fresh_row_id`](https://github.com/probcomp/bayeslite/blob/master/src/core.py#L416) synthesizes a fresh row for an unobserved member of the statistical population by always returning one greater than the number of rows in the generator table.

While this behavior is appropriate for crosscat since it never remembers fake rowids, it is inappropriate for a general GPM. In particular, a GPM may keep track of every `rowid` it has ever seen, even during queries (i.e invoking `SIMULATE` with a particular `rowid = x` will cause a permanent change to the internal state of the GPM).

One simple example is a very simple GPM for a random variable `x` in venture:

`(assume x (mem (lambda (rowid) (normal 0 1))))`

One query with `rowid=max(rowid)+1` followed by another query with `rowd=max(rowid)+1` will cause a failure mode. One correct behavior is to synthesize `rowid ~ U[0,1]` to ensure the integrity of uniqueness.

**Comment by riastradh-probcomp** [comment]
That sounds like a broken metamodel to me.  Simulate should not have side effects other than on the random state.

**Comment by luac** [comment]
Agreed with @riastradh-probcomp. Venture's sample should have the appropriate semantics here.

(It does have a drawback in that if you intend to simulate and then insert a bunch of rows, and you do simulate and insert as separate operations, then the inserted row will not necessarily have the same per-row latents that it was simulated with. But this is a separate issue. I don't know if Bayeslite has an answer to this; maybe it should be another ticket?)

**Comment by fsaad** [comment]
@axch and I had discussion in past whether `simulate` obeyed `sample` or `predict` semantics. Keeping this ticket open until we explicitly express the difference in the design document (ie a GPM which does `predict` on `simulate` and changes its internal staet is violating the contract). Currently we do not enforce that constraints per se.

**Comment by fsaad** [comment]
The implementation of `VsCGpm` goes to great pains to ensure this invariant is maintained: https://github.com/probcomp/cgpm/blob/master/src/venturescript/vscgpm.py#L104-L106
