### ISSUE TITLE
Use ieee_exp not math.exp

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#281]
Large values of `r` (when it is a density) cause a math range error.
```
File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bqlfn.py",
line 293, in bql_column_value_probability
    return math.exp(r)
OverflowError: math range error
```
Should be `ieee`.

**Comment by fsaad** [comment]
Preferably soon i.e. before merging the foreign predictor branch in `bdbcontrib`.

**Comment by fsaad** [comment]
Fixed by #282

**Comment by riastradh-probcomp** [comment]
We ought to change this so that it returns log-domain values anyway.

**Comment by fsaad** [comment]
Do you mean `bql_column_value_probability` to `bql_column_value_log_probability`? The GPM interface is now returning values in logspace.
