### ISSUE TITLE
NOT NULL constraint failed: bayesdb_crosscat_diagnostics.logscore

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#284]
```
bayeslite> ANALYZE solvers FOR 15 MINUTES wait;
Traceback (most recent call last):
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/shell/core.py", line 133, in default
    cursor = bql.execute_phrase(self._bdb, phrase)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bql.py", line 459, in execute_phrase
    ckpt_seconds=phrase.ckpt_seconds)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/metamodels/crosscat.py", line 1073, in analyze_models
    'iterations': theta['iterations'],
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py", line 236, in sql_execute
    self.sql_tracer, self._do_sql_execute, string, bindings)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py", line 178, in _maybe_trace
    return meth(string, bindings)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py", line 239, in _do_sql_execute
    return bql.BayesDBCursor(self, self.sqlite3.execute(string, bindings))
IntegrityError: NOT NULL constraint failed: bayesdb_crosscat_diagnostics.logscore
```

Suspicion this happened because I have some columns of all `None` - but we should be able to do something about that case.

**Comment by riastradh-probcomp** [comment]
This is a bug in Crosscat: somehow analyze is returning `None`, or more likely NaN, for some logscore.

**Comment by fsaad** [comment]
Oh boy just got it again, even after nullifying and ignoring columns of all `None`.

**Comment by riastradh-probcomp** [comment]
I don't expect any particular `None`s in the table have anything to do with this.  It sounds like an invalid floating-point operation in the logscore calculation which yields NaN.

One way to try to debug it would be to trap the invalid-operation exception in Crosscat, if code inspection doesn't find it.

Can you show your table's M_c?  (`select metadata_json from bayesdb_crosscat_metadata where generator_id = ?`)

It might also be helpful to apply this patch to Crosscat: 
[assertnotnan.txt](https://github.com/probcomp/bayeslite/files/21211/assertnotnan.txt)

**Comment by gregory-marton** [comment]
@fsaad, can you take next steps, or provide more info to independently reproduce?

**Comment by gregory-marton** [comment]
One output from the suggested assertion:
https://docs.google.com/document/d/1fpnbR4AxuWE0NetllswHRUFMD0hk3PqNCdvCnY8u2y8/edit

**Comment by gregory-marton** [comment]
https://github.com/probcomp/crosscat/commit/f91197c5f7fe24f7c3af47823d187580a1e138b1
https://github.com/probcomp/bayeslite/commit/19b8071ce3dcc6b5669bac0affd94c08fff67af5
as additional diagnostics, and improved guessing in https://github.com/probcomp/bayeslite/commit/8b87fd10cbb7bbb85badbfb15e88ab470757aa81
to help avoid the problem in the first place. It covers all instances I've run across so far, namely all-nulls, and all-null-or-same-value. It's still super easy to get this error in a repeatable way by specifying the column type for such a degenerate column as numeric, rather than letting guess ignore it.

**Comment by riastradh-probcomp** [comment]
It sounds like there is a bug in *Crosscat* causing NaN to come out.  If we mask the bug in bayeslite, that will make it harder to find the bug in Crosscat.  Did you trip over the assert you added in Crosscat, or only the one in bayeslite?

**Comment by BelhalK** [comment]
Same bug happening on a remote host but not on my local computer 
What do you advise?

![not null not null constraint failed](https://cloud.githubusercontent.com/assets/15817944/12796777/9281f7ea-ca8e-11e5-8d85-527ce0752133.png)

**Comment by gregory-marton** [comment]
updating to the latest bayeslite / bdbcontrib, ahead of the releases
(because I haven't released 0.1.6 yet, and it's fixed ahead of 0.1.5)

On Wed, Feb 3, 2016 at 3:55 PM, Belhal KARIMI <notifications@github.com>
wrote:

> Same bug happening on a remote host but not on my local computer
> What do you advise?
>
> [image: not null not null constraint failed]
> <https://cloud.githubusercontent.com/assets/15817944/12796777/9281f7ea-ca8e-11e5-8d85-527ce0752133.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/probcomp/bayeslite/issues/284#issuecomment-179461208>.
>



-- 
Gregory Marton
--
gremio@mit.edu
617-858-0775
http://csail.mit.edu/~gremio/cal

**Comment by asilversempirical** [comment]
I just tripped this bug in bayeslite 0.1.8. It sounds like that's unexpected. Do you want me to dump any information?

**Comment by riastradh-probcomp** [comment]
Fixing this requires finding where Crosscat is getting NaN in the logscore calculation.  Last time I tried to track down sources of this symptom I liberally sprinkled `assert(!isnan(...))` throughout Crosscat, starting in State.cpp's `State::transition_*` functions.

Here is an example of a bug that could cause this symptom (a bug which bayeslite's logic to guess statistical types tries to avoid in some cases, so it may not be the bug you're encountering): https://github.com/probcomp/crosscat/issues/85

**Comment by asilversempirical** [comment]
Got it. I was just confused by Grem's comment that "...it's fixed ahead of 0.1.5"

Is there a straightforward workaround in the meantime? I could manually ignore the column if it's easy to figure out what column it's choking on, but I don't get much in the ways of debug output. Is that included in the output of that patch?

**Comment by riastradh-probcomp** [comment]
Probably Grem was referring to the bayeslite statistical type guessing heuristic to avoid modelling constant columns.

Unfortunately, at the time the NaN comes flying out of Crosscat, it is not associated with any particular column.  We don't know all the conditions of column values (if they are isolated to individual columns!) under which Crosscat will compute NaN for a logscore.  We know at least one condition: a constant column.  There are more conditions which have not been fully analyzed, such as <https://github.com/probcomp/bayeslite/issues/388>, which has a lead you might follow about normal sufficient statistics and update_continuous_hypers.

**Comment by riastradh-probcomp** [comment]
Of course, if you can discern that you have a constant column and then skip modelling it, that would be the easiest way to work around this!  But if you don't obviously have a constant column then I'm afraid it will take some more work.

**Comment by alxempirical** [comment]
@asilversempirical, can you get a backtrace if you recompile crosscat with [FP exceptions turned on](http://stackoverflow.com/a/3616017/1941213) in State.cpp?

**Comment by asilversempirical** [comment]
Performance got so bad after enabling FP exceptions that it couldn't initialize the models. I never got to analyze to try to trigger the issue.

**Comment by alxempirical** [comment]
Thanks for trying it.  I'll try it on some of the smaller test cases I ran into on the other thread when I get some time.

**Comment by fsaad** [comment]
https://github.com/probcomp/bayeslite/commit/d2376c134942f40b3305cdf972be708e7404f25a
