### ISSUE TITLE
Option: Feed BayesDB's entropy into the crosscat engine

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#292]
(at registration time?) instead of requiring the user to supply external entropy to crosscat if they want determinism

**Comment by fsaad** [comment]
The `cgpm` engine takes entropy from bayeslite:
https://github.com/probcomp/bayeslite/blob/master/src/metamodels/cgpm_metamodel.py#L559

The `crosscat.py` metamodel implementation is largely deprecated now.
