### ISSUE TITLE
bayesdb-demo dies with "Missing application_id"

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#314]
From Kevin Riggle:

I pip installed it and after a bit of fiddling making sure boost was
installed now have the kernel running.  Now bayesdb-demo dies on the
call to bayeslite.bayesdb_open with 'EnvironmentError: Missing
application_id in sqlite3' at line 125 in
~/bayeslite-virtualenv/lib/python2.7/site-packages/bayeslite/schema.py

This is Python 2.7.5 on OS X Mavericks.

(Full trace from the iPython Notebook below.)

- Kevin

/Users/kriggle/bayeslite-virtualenv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
---------------------------------------------------------------------------
EnvironmentError                          Traceback (most recent call last)
<ipython-input-1-22181d754dfd> in <module>()
      6 # Load the satellites snapshot into a local instance of bayeslite
      7
----> 8 satellites_bdb = bayeslite.bayesdb_open(pathname='satellites.bdb')
      9
     10 # Define a utility procedure to conveniently query satellites_bdb

/Users/kriggle/bayeslite-virtualenv/lib/python2.7/site-packages/bayeslite/bayesdb.pyc in bayesdb_open(pathname, builtin_metamodels, seed, version, compatible)
     54         builtin_metamodels = True
     55     bdb = BayesDB(bayesdb_open_cookie, pathname=pathname, seed=seed,
---> 56         version=version, compatible=compatible)
     57     if builtin_metamodels:
     58         metamodel.bayesdb_register_builtin_metamodels(bdb)

/Users/kriggle/bayeslite-virtualenv/lib/python2.7/site-packages/bayeslite/bayesdb.pyc in __init__(self, cookie, pathname, seed, version, compatible)
     96         self._np_prng = numpy.random.RandomState(nprseed)
     97         schema.bayesdb_install_schema(self.sqlite3, version=version,
---> 98             compatible=compatible)
     99         bqlfn.bayesdb_install_bql(self.sqlite3, self)
    100

/Users/kriggle/bayeslite-virtualenv/lib/python2.7/site-packages/bayeslite/schema.pyc in bayesdb_install_schema(db, version, compatible)
    123         row = cursor.next()
    124     except StopIteration:
--> 125         raise EnvironmentError('Missing application_id in sqlite3.')
    126     else:
    127         application_id = row[0]

EnvironmentError: Missing application_id in sqlite3.

**Comment by riastradh-probcomp** [comment]
Sounds like the version of sqlite3 on Mavericks is too old -- pre-3.7.17.  That's frustrating.

Aside: it sounds like we also can't rely on TLS via Python on that platform.

**Comment by riastradh-probcomp** [comment]
Another reason to switch to apsw (#92): I think it uses its own copy of sqlite3, so it may not rely on whatever OS X already has installed.

**Comment by riastradh-probcomp** [comment]
Blocked on #92.

**Comment by riastradh-probcomp** [comment]
This should be fixed now once we build a new OS X .app.

**Comment by raxraxraxraxrax** [comment]
Confirmed that this worked in an 0.1.4 alpha build; closing unless we find out otherwise.
