### ISSUE TITLE
Document how to sign and push the ipynb and bdb

### ISSUE THREAD

**Issue by gregory-marton** [probcomp/bayeslite#317]

**Comment by riastradh-probcomp** [comment]
B=/path/to/bdbcontrib
    cd /path/to/demo
    $B/pythenv.sh python $B/src/demo/pack.py MAGIC /path/to/seckey > /path/to/pack

where MAGIC is the string `I am a human on a single-user machine`, and /path/to/seckey is a file containing the secret signing key.

Then upload /path/to/pack to the web site.

**Comment by riastradh-probcomp** [comment]
We no longer use this system.
