### ISSUE TITLE
axes.color_cycle is deprecated and replaced with axes.prop_cycle

### ISSUE THREAD

**Issue by raxraxraxraxrax** [probcomp/bayeslite#321]
When running the following code in the iPython Satellites notebook:

import matplotlib.pyplot as plt
%matplotlib inline
bdbcontrib.histogram(satellites_bdb, 'SELECT dry_mass_kg, class_of_orbit FROM satellites', bins=35, normed=True);

I get the following warning:

/Applications/Bayeslite-bayes0.1.4a20151203.post1+g6504c8c-bdbco0.1.3.post2+gdd91b2b.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/**init**.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

**Comment by fsaad** [comment]
I believe this warning no longer arises with matplotlib==1.5.1 on Ubuntu 16.04, our release platform.
