### ISSUE TITLE
Test to make sure copyright headers are set to current year

### ISSUE THREAD

**Issue by raxraxraxraxrax** [probcomp/bayeslite#323]
We should have an automated test to make sure the copyright year is set correctly. (Do we need to duplicate this test for any other products?)

**Comment by gregory-marton** [comment]
I'm updating my script that packages things up for pypi. I'm going to add that script to packaging.

**Comment by gregory-marton** [comment]
That script, which includes this copyright test, is now here: 
https://github.com/probcomp/packaging/blob/master/pypi/update.sh
