### ISSUE TITLE
Possible matplotlib/venv issue

### ISSUE THREAD

**Issue by raxraxraxraxrax** [probcomp/bayeslite#324]
This is from my lab notebook. A couple of weeks ago, RIchard helped me build and run bayeslite in a virtual environment on my laptop, since it was fialing outside of a virtual environment. This mostly worked, but trying to do anything with matplotlib gave me this error:

import matplotlib.pyplot as plt
 
%matplotlib inline
 
bdbcontrib.histogram(satellites_bdb, 'SELECT dry_mass_kg, class_of_orbit FROM satellites', bins=35, normed=True);
 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-8a4c0f6a0dcf> in <module>()
----> 1 import matplotlib.pyplot as plt
      2 get_ipython().magic(u'matplotlib inline')
      3 bdbcontrib.histogram(satellites_bdb, 'SELECT dry_mass_kg, class_of_orbit FROM satellites', bins=35, normed=True);
 
/Users/rax/build-bayesdb/bayesdb-0.1.3-head/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    112
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115
    116 _IP_REGISTERED = None
 
/Users/rax/build-bayesdb/bayesdb-0.1.3-head/lib/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33
     34     # Things we pull in from all backends
 
/Users/rax/build-bayesdb/bayesdb-0.1.3-head/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py in <module>()
     22
     23 import matplotlib
---> 24 from matplotlib.backends import _macosx
     25
     26
 
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

I discovered http://matplotlib.org/1.5.0/faq/virtualenv_faq.html which has some workarounds at the bottom. I put the python script into my virtualenv and started bayesdb-demo as follows: 

$ frameworkpython ~/build-bayesdb/bayesdb-0.1.3-head/bin/bayesdb-demo

But still got the same error. I'm not sure if this is a bayesdb issue or an issue with something Richard or I did, but I wanted to file a ticket in case someone else runs into the same thing. (My personal needs were met by an 0.1.4 alpha .app build.)

**Comment by gregory-marton** [comment]
Can we try this again today with an 014 candidate? @raxraxraxraxrax are you in today, or wfh?

**Comment by gregory-marton** [comment]
I think @raxraxraxraxrax just succeeded.

**Comment by raxraxraxraxrax** [comment]
I hadn't actually succeeded yet when that was written, but shortly thereafter, I confirmed this worked on the machine where I had the issue with an earlier build.
