### ISSUE TITLE
installation crash

### ISSUE THREAD

**Issue by TjrGithub** [probcomp/bayeslite#325]
How to reproduce the crash:
$ uname -a
CYGWIN_NT-6.1-WOW TINY108 2.3.1(0.291/5/3) 2015-11-14 12:42 i686 Cygwin
$ rm -rf env/
$ virtualenv -p python3 env/
$ env/bin/python --version
Python 3.4.3
$ ./env/bin/pip install bayeslite bdbcontrib
Collecting bayeslite
  Using cached bayeslite-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-9on0ruro/bayeslite/setup.py", line 77
        print 'writing %s' % (path,)
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9on0ruro/bayeslite

**Comment by gregory-marton** [comment]
Right, it's not Python 3 compatible. Try a Python 2 >= 2.7.9

This is working as intended for now.

Gregory Marton
617-858-0775
http://csail.mit.edu/~gremio/cal

**Comment by TjrGithub** [comment]
Thank you!

Am 04.01.2016 um 12:06 schrieb Gregory Marton - notifications@github.com:
> Right, it's not Python 3 compatible. Try a Python 2 >= 2.7.9
>
> This is working as intended for now.
>
> Gregory Marton
> 617-858-0775
> http://csail.mit.edu/~gremio/cal
