### ISSUE TITLE
Crosscat installation problem

### ISSUE THREAD

**Issue by prateekpg2455** [probcomp/bayeslite#331]
I have been trying to install BayesDB using python2.7and it gets stuck at crosscat installation. I already have it and all the dependencies required by it are already there. 

Here is the error that I got:
```
Installed /usr/local/lib/python2.7/site-packages/bayeslite-0.1.4.post1+gfb66992-py2.7.egg
Processing dependencies for bayeslite==0.1.4.post1+gfb66992
Searching for crosscat>=0.1.48
Reading https://pypi.python.org/simple/crosscat/
No local packages or download links found for crosscat>=0.1.48
error: Could not find suitable distribution for Requirement.parse('crosscat>=0.1.48')
```

This is what I get when I try installing crosscat:
```
Requirement already satisfied (use --upgrade to upgrade): crosscat in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): cython>=0.20.1 in /usr/local/lib/python2.7/site-packages (from crosscat)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /usr/local/lib/python2.7/site-packages (from crosscat)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from crosscat)
```

**Comment by gregory-marton** [comment]
That's neat. I didn't think I had published that bayeslite 0.1.4 version. Where'd you get it? Did you install from the git repo? In that case, you'll want the head version of crosscat, bayeslite-apsw, and bdbcontrib too.

**Comment by prateekpg2455** [comment]
Yeah I cloned the repository. Is there any other way to install it?

**Comment by gregory-marton** [comment]
The usual is via pip, but the repo is fine, you just then need all the relevant repos, as noted above.

**Comment by prateekpg2455** [comment]
I tried installing it with pip too. Its the same error:
```
Collecting bayeslite-apsw>=3.8.0 (from bayeslite)
  Downloading bayeslite-apsw-3.9.2-r1+pypiisbroken.tar.gz (1.9MB)
    100% |████████████████████████████████| 1.9MB 252kB/s
Collecting crosscat>=0.1.48 (from bayeslite)
  Could not find a version that satisfies the requirement crosscat>=0.1.48 (from bayeslite) (from versions: 0.1.0.dev0, 0.1.2, 0.1.5, 0.1.25, 0.1.27, 0.1.28, 0.1.36, 0.1.43)
No matching distribution found for crosscat>=0.1.48 (from bayeslite)
```

**Comment by gregory-marton** [comment]
Start with crosscat. Clone it, build it (you need to have boost, and
specify BOOST_ROOT) and install it. Then bayeslite-apsw, then bayeslite,
then bdbcontrib.

Gregory Marton
617-858-0775
Calendar: http://csail.mit.edu/~gremio/cal
Plus: http://goo.gl/Ne09o
Web: http://csail.mit.edu/~gremio

**Comment by prateekpg2455** [comment]
That works! Thanks.
