### ISSUE TITLE
test suite no longer covers any of legacy_models.py???

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#350]

**Comment by fsaad** [comment]
What is `legacy_models.py`?

**Comment by riastradh-probcomp** [comment]
Date: Mon, 14 Nov 2016 16:29:19 -0800
   From: F Saad <notifications@github.com>

   What is `legacy_models.py`?

Not important any more!  It previously read models from the old
BayesDB and converted them to bayeslite's format.  I seem to recall
deleting bits of it, if not the whole thing, over the summer.
