### ISSUE TITLE
Type of Database?

### ISSUE THREAD

**Issue by prateekpg2455** [probcomp/bayeslite#357]
What type of database can I use with it? How can I get .bdb database? 

Is there a way to convert .csv to .bdb?

**Comment by riastradh-probcomp** [comment]
You get a .bdb database by opening one that doesn't exist yet with `bayesdb_open` in Python, from the `bayeslite` module.

You can import a CSV file into your database by calling `bayesdb_read_csv_file`.

**Comment by riastradh-probcomp** [comment]
You can also import any other data format you want if you have Python code to parse it by executing standard SQL code via the Python API -- it's just sqlite3 under the hood, under all the BQL stuff:

    bdb.sql_execute('CREATE TABLE ...')
    for x, y, z in ...:
        bdb.sql_execute('INSERT INTO ... VALUES (?,?,?)', (x, y, z))

The CSV import works this way, as does pandas dataframe import.  Those are the only data formats we provide code to import, but you can write any others you want.

**Comment by prateekpg2455** [comment]
I have been trying to understand the use of bayesdb_read_csv_file from the code but I am confused regarding the argument bdb which it requires. I am also not sure about the name of the table that I have in csv. Its a csv file with headers and it is on sheet1. 

Can you give an example?

**Comment by riastradh-probcomp** [comment]
Use

    with bayesdb_open('foo.bdb') as bdb:
        ...

to create or reopen the database foo.bdb and then refer to it in the ellipsis using the local variable `bdb`.

The name of the table for `CREATE TABLE` or for `bayesdb_read_csv_file` is your choice.  It does not need to correspond to anything about the CSV file.  You will just need to use the same name to query the table, or to create and analyze generative models for it.

**Comment by gregory-marton** [comment]
Operationally, if you have a recent bdbcontrib, it might be easiest to:

    from bdbcontrib.recipes import quickstart;
    population_object = quickstart('population_name', csv_path='population.csv')
    population_object.analyze(minutes=5)
    population_object.q('''ESTIMATE ...''')

**Comment by prateekpg2455** [comment]
I tried what @riastradh-probcomp  suggested and got this error. How can I find out the table name in csv file?

<code>
In [14]: bayesdb_read_csv_file(bayesdb_open('foo.db'), 'sheet1' , datafile)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-7f5cf8d7d66f> in <module>()
----> 1 bayesdb_read_csv_file(bayesdb_open('foo.db'), 'sheet1' , datafile)

/usr/local/lib/python2.7/site-packages/bayeslite-0.1.4.post1+gfb66992-py2.7.egg/bayeslite/read_csv.pyc in bayesdb_read_csv_file(bdb, table, pathname, header, create, ifnotexists)
     36     with open(pathname, 'rU') as f:
     37         bayesdb_read_csv(bdb, table, f, header=header, create=create,
---> 38             ifnotexists=ifnotexists)
     39
     40 def bayesdb_read_csv(bdb, table, f, header=False,

/usr/local/lib/python2.7/site-packages/bayeslite-0.1.4.post1+gfb66992-py2.7.egg/bayeslite/read_csv.pyc in bayesdb_read_csv(bdb, table, f, header, create, ifnotexists)
     60                 raise ValueError('Table already exists: %s' % (repr(table),))
     61         elif not create:
---> 62             raise ValueError('No such table: %s' % (repr(table),))
     63         reader = csv.reader(f)
     64         line = 1

ValueError: No such table: 'sheet1'
</code>

**Comment by gregory-marton** [comment]
I think you think you're supposed to use an existing db file where we're saying "bdb". Instead, the bdb is something that we can create from your .csv file.

**Comment by prateekpg2455** [comment]
@gregory-marton It seems like there are lot of libraries that are being used. I have been trying to understand use of those. Do you guys have a manual/ document describing the use and algorithms being used in it? If yes, where can I find it?

**Comment by riastradh-probcomp** [comment]
You need to pass `create=True` to `bayesdb_read_csv_file` if you want it to additionally create the table first.

**Comment by gregory-marton** [comment]
There are many algorithms and intended use cases. Which documentation are you asking for? The best algorithm descriptions will be in academic papers, but I'm not sure that's what you're asking.

**Comment by riastradh-probcomp** [comment]
The reference manual for `bayesdb_read_csv_file` is right there -- in the docstring.  To build a single document containing the manual, run `make doc` in the top-level source code of bayeslite, and find it in `build/doc/`.  (You will need sphinx and latex to build it.)

**Comment by prateekpg2455** [comment]
No. Only the ones implemented here. I am just looking for the names of the algorithms/inference methods so that I know what's going on in the backend.

**Comment by gregory-marton** [comment]
@riastradh-probcomp is describing the fine-grained approach. If you want to get started quickly with a new dataset, I would suggest exporting that dataset to csv, and using the bdbcontrib.recipes.quickstart approach.

**Comment by gregory-marton** [comment]
To easily read docstrings, use the python help facility: 
help(bayesdb_read_csv_file) or e.g. help(bdbcontrib.recipes)

**Comment by prateekpg2455** [comment]
Thanks guys!! I think I am getting it. The command worked but I don't know what name of table did it store it as ?

```
bayesdb_read_csv_file(bayesdb_open('foo.db'), 'sheet1' , datafile, create =True, header = True)
```
I want to run 
```
bdb.execute("SELECT * FROM TABLENAME")
```

**Comment by gregory-marton** [comment]
I think what you said above is to create the file foo.db as the new bdb, inside it create a "sheet1" table, and into it put the contents of datafile (which has a header row). So from that, TABLENAME would be "sheet1".

**Comment by prateekpg2455** [comment]
I am getting a 
```
SQLError: SQLError: no such table: sheet1
```

**Comment by riastradh-probcomp** [comment]
with bayesdb_open('foo.bdb') as bdb:
        bayesdb_read_csv_file(bdb, 'sheet1', datafile, create=True, header=True)
        for row in bdb.execute('select * from sheet1'):
            print row

**Comment by prateekpg2455** [comment]
Perfect!! Thanks a lot!
