### ISSUE TITLE
Trying to create temp table that already exists gives confusing 'EOF in multi-line string' error

### ISSUE THREAD

**Issue by raxraxraxraxrax** [probcomp/bayeslite#358]
The workaround is to just drop the table and then recreate it, but this error message could be _much_ better.

BQL [
CREATE TEMP TABLE satellite_purpose AS
SIMULATE country_of_operator, purpose FROM satellites_cc
GIVEN Class_of_orbit = 'GEO', Dry_mass_kg = 500 
LIMIT 1000;
] [()]
ERROR: FROM BQL [
CREATE TEMP TABLE satellite_purpose AS
SIMULATE country_of_operator, purpose FROM satellites_cc
GIVEN Class_of_orbit = 'GEO', Dry_mass_kg = 500 
LIMIT 1000;
] [()]
Traceback (most recent call last):

 File "/Applications/Bayeslite-v0.1.4.app/Contents/MacOS/venv/lib/python2.7/site-packages/bdbcontrib/recipes.py", line 123, in q
   res = self.bdb.execute(query_string, args)

 File "/Applications/Bayeslite-v0.1.4.app/Contents/MacOS/venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 214, in execute
   self.tracer, self._do_execute, string, bindings)

 File "/Applications/Bayeslite-v0.1.4.app/Contents/MacOS/venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 219, in _maybe_trace
   tracer, meth, string, bindings)

 File "/Applications/Bayeslite-v0.1.4.app/Contents/MacOS/venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 232, in _trace_articulately
   cursor = meth(string, bindings)

 File "/Applications/Bayeslite-v0.1.4.app/Contents/MacOS/venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 263, in _do_execute
   cursor = bql.execute_phrase(self, phrase, bindings)

 File "/Applications/Bayeslite-v0.1.4.app/Contents/MacOS/venv/lib/python2.7/site-packages/bayeslite/bql.py", line 96, in execute_phrase
   (repr(phrase.name),))

BQLError: Name already defined as table: 'satellite_purpose'

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))

**Comment by riastradh-probcomp** [comment]
The error that our software reports is:

    BQLError: Name is already defined as table: 'satellite_purpose'

The remainder of the scary text,

    ERROR: An unexpected error occurred while tokenizing input
    The following traceback...

is due to a bug in ipython over which we have no control, unless someone wants to sit down and debug ipython and find a way to work around it.

How could our error message be clearer?

**Comment by raxraxraxraxrax** [comment]
> How could our error message be clearer?

It could not have a separate, scarier error message at the end? :)

In all seriousness, would it be worth catching and handling this and similar exceptions instead of producing a traceback?

**Comment by riastradh-probcomp** [comment]
We can't catch it because it happens outside any code that we run.  It is a bug in ipython.  If someone wants to debug that, maybe we can find some way to work around it -- but I don't expect there to be any nondestructive useful change we can make to our code that avoids it without fixing the ipython bug upstream, or installing some custom ipython kernel or something.  (There could be; I'm just guessing there isn't.)

**Comment by riastradh-probcomp** [comment]
Here's an earlier instance of the same issue: https://github.com/probcomp/bayeslite/issues/174

**Comment by fsaad** [comment]
iventure now captures the full stack and stores it in a log file in the user's home directory, and reports a one-line error message (when possible, for e.g. BQLErrors) to stderr.

https://github.com/probcomp/iventure/blob/dd723f652b7e5688590cdda3de0b1968da872a09/src/magics.py#L181-L207
