### ISSUE TITLE
bdbcontrib.pairplot fails with unhelpful error message when matplotlib not imported

### ISSUE THREAD

**Issue by raxraxraxraxrax** [probcomp/bayeslite#359]
bdbcontrib.pairplot(satellites.bdb, 'SELECT Apogee_km, Perigee_km FROM satellites');

/Volumes/Bayeslite/Bayeslite-v0.1.4.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")

In theory, falling back to another renderer should be fine (and googling this error message suggests that it could at least theoretically work), but in practice on my Mac, the Python application bounces in the dock for a while and no diagrams ever show up in the notebook.

**Comment by gregory-marton** [comment]
Try explicitly using the pdf renderer right off?

**Comment by raxraxraxraxrax** [comment]
Can you tell me how to do that, please? :)

**Comment by gregory-marton** [comment]
There are a bunch of ways. http://matplotlib.org/faq/usage_faq.html
For example, right after importing matplotlib for the first time, matplotlib.use('PDF')

**Comment by riastradh-probcomp** [comment]
Helpfully, I think it *must* be right after importing matplotlib and before importing matplotlib.pyplot -- you can't do it dynamically because making any backend choice wedges matplotlib into using that choice for the remaining lifetime of your process.

**Comment by raxraxraxraxrax** [comment]
So, hilariously, the actual issue here was that I didn't have matplotlib imported at all.

**Comment by riastradh-probcomp** [comment]
It will have been imported by bdbcontrib.whatever.  (So you need to import matplotlib first and do matplotlib.use(...) before you can import any plotting code from bdbcontrib...)

**Comment by raxraxraxraxrax** [comment]
I'm not entirely sure where that leaves this bug report. Ideally, the error message should have told me to import matplotlib, but I'm not sure how reasonable that is to ask for. Maybe it's a documentation issue that this command depends on typing "import matplotlib" into your notebook somewhere before using it?

**Comment by riastradh-probcomp** [comment]
Hold on -- are you saying just doing `import matplotlib` explicitly just before calling `bdbcontrib.pairplot`, without changing the back end, causes this to work from end-to-end without that failure?  That sounds completely crazy, because as I mentioned bdbcontrib modules already import matplotlib; otherwise, how would control ever enter the matplotlib code?

**Comment by raxraxraxraxrax** [comment]
Specifically, running this code already in the notebook:

import matplotlib.pyplot as plt
%matplotlib inline
bdbcontrib.histogram(satellites.bdb, 'SELECT dry_mass_kg, class_of_orbit FROM satellites', bins=35, normed=True);

appears to be required, at least in my notebook. I think it's the "%matplotlib inline" that does it.

**Comment by riastradh-probcomp** [comment]
That sounds more plausible, then.  Telling people to do `%matplotlib inline` is probably worthwhile, although I don't know the right place to do that offhand.

**Comment by fsaad** [comment]
bdbcontrob.pairplot has been replaced with jsviz.pairplot:
https://github.com/probcomp/iventure/commit/06aff9d006884f8e5e823f70b6c96f9cd4ea3440#diff-6ddf123a958afaa74748126cea16993d
