### ISSUE TITLE
Replace 'BQL' by 'MML' in quickstart output 

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bayeslite#364]
![capture d ecran 2016-01-28 a 11 12 55](https://cloud.githubusercontent.com/assets/15817944/12650256/1aa4a9a8-c5b0-11e5-88d3-f004bae60595.png)

The output of quickstart is returning BQL instead of MML

**Comment by riastradh-probcomp** [comment]
As I understand it -- though the three-letter acronym 'MML' and other related three-letter acronyms are consistently nebulous --, 'MML' refers only to the little language inside CREATE GENERATOR where you specify a hypothesis space for a generator, and maybe also ANALYZE where you could conceivably specify an inference program except it's currently very limited.

**Comment by gregory-marton** [comment]
584719c. Nevermind, didn't see Riastradh's response. Rolled back.
Yeah, BQL is pretty well defined. Will leave it for now.
