### ISSUE TITLE
Change the terminology of ITERATION/TRANSITION by a clearer expression (Gibbs sampling?)

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bayeslite#365]
The terms ITERATIONS or TRANSITIONS in q(bdb,"ANALYZE %g FOR 10 ITERATIONS WAIT;") are somehow misleading or not comprehensible.
We should adopt another word such as 'Gibbs sampling' for instance.

**Comment by riastradh-probcomp** [comment]
The reason we don't use something more specific in BQL itself is that we are not committing to any particular transition operator in BQL -- it is up to the metamodel to spend the computational cost, counted in generic iterations, as it pleases.
