### ISSUE TITLE
bayeslite test_logging.py fails with AssertionError

### ISSUE THREAD

**Issue by madeleineth** [probcomp/bayeslite#368]
Synced to 367a679523cba8df2d9555c1fcddba7a58cf411a.

    >       assert 1 == len(slowstub.calls)
    E       assert 1 == 0
    E        +  where 0 = len([])
    E        +    where [] = <test_loggers.StubCallable instance at 0x7fdaad5b47e8>.calls
    
    tests/test_loggers.py:130: AssertionError

To replicate:

(1) cd into an empty directory.
(2) `git clone git@github.com:probcomp/bayeslite.git`
(3) Make a file called `Dockerfile.fail` with this.

    FROM ubuntu:trusty
    ENV DEBIAN_FRONTEND noninteractive
    RUN apt-get update -y
    RUN apt-get install -y python-pip python-dev libboost-random1.55-dev
    RUN pip install numpy cython
    RUN pip install pytest pexpect pandas requests bayeslite-apsw
    RUN pip install crosscat
    COPY bayeslite /var/build/bayeslite
    RUN apt-get install -y libxft-dev libpng-dev
    RUN pip install matplotlib
    WORKDIR /var/build/bayeslite
    RUN ./check.sh

(4) `docker pull ubuntu:trusty`
(5) `docker build -t bayeslitefail -f Dockerfile.fail .`

**Comment by madeleineth** [comment]
I've now seen this succeed on trusty (14.04) and fail on wily (15.10), so it's not deterministic, and it's not Ubuntu-version-dependent.

Here's the Dockerfile for wily:

> FROM ubuntu:wily
> ENV DEBIAN_FRONTEND noninteractive
> RUN apt-get update -y
> RUN apt-get install -y python-pip python-dev libboost-random-dev libxft-dev libpng-dev python-numpy
> RUN pip install cython pytest pexpect pandas requests bayeslite-apsw matplotlib crosscat
> COPY bayeslite /var/build/bayeslite
> WORKDIR /var/build/bayeslite
> RUN ./check.sh

**Comment by gregory-marton** [comment]
I might have fixed this in 3b8d8c4. Would love confirmation.

**Comment by gregory-marton** [comment]
We now have a docker-based test that shows that this is fixed.
https://probcomp-4.csail.mit.edu/job/bayeslite-docker-runtests/
