### ISSUE TITLE
Feature Request : quick_describe_columns should return the names of the columns it dropped

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bayeslite#369]
quick_describe_columns should return a table with the columns names and the number of columns it has dropped from the original table to build the generator

**Comment by gregory-marton** [comment]
Rather, it should show "IGNORED" as a statistical type, alongside
"NUMERICAL" and "CATEGORICAL". Simply not listing those ignored columns is
not a great user experience.

**Comment by fsaad** [comment]
quick_describe_columns is no longer maintained.
