### ISSUE TITLE
Conditional probability yields unexpected values

### ISSUE THREAD

**Issue by gregory-marton** [probcomp/bayeslite#380]
Two adjacent evaluations of conditional probability that age=8 give weight=8, one by explicitly specifying the column, and the other by evaluating the conditional probability for all columns that their value = 8, yield different results.

The probability that `weight=8 given weight=16` is nonzero.

See the (soon to be) commented-out test in test_bql.py test_conditional_probability.

**Comment by alxempirical** [comment]
This happens for 

```
estimate probability of value 8 given (weight = 16) from columns of t1_cc
```

but for 

```
estimate probability of weight=8 given (weight=16) by t1_cc
```

the value `None` is returned, which may be reasonable, though 0 sounds better.

**Comment by gregory-marton** [comment]
https://github.com/probcomp/crosscat/issues/34

**Comment by riastradh-probcomp** [comment]
This turns out to be a trivialler bug than I thought.

The bayeslite compiler simply forgot to pass on the constraint `weight = 16` when compiling `probability of value 8 given (weight = 16)`.

**Comment by riastradh-probcomp** [comment]
It is not clear to me what `PROBABILITY OF weight = 8 GIVEN (weight = 8)` should be, when `weight` is a continuous variable -- it is not obvious that 1 is actually a reasonable answer to demand, even if the density is normalized.  But for discrete variables, it may be reasonable to demand that it be 1, so in the branch I created to fix this I added a test for that.
