### ISSUE TITLE
division by zero error in Crosscat when there are no models is confusing

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#386]
Everywhere this might happen, we should report a more comprehensible error message.

**Comment by BelhalK** [comment]
Agreed. 
People could think their dataset contains zero and/or missing values (which is not an issue for crosscat) whereas the actual issue is that there generator is empty (no models)

**Comment by fsaad** [comment]
Duplicate of https://github.com/probcomp/bayeslite/issues/363
