### ISSUE TITLE
Similarity query should take a key as argument instead of using default row indexes

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bayeslite#387]
**Similarity of pairwise rows** is showing the score of similarity using id of the pairwise rows.
For readability purposes, we should be able to use a variable name (like an ID) instead of these indexes and not being obliged to do it pre or post query

**Comment by riastradh-probcomp** [comment]
estimate name, similarity to (name='Thelma') from pairwise rows of t

**Comment by BelhalK** [comment]
Thanks. it is working I'm closing
NB: 'estimate name, similarity to (name='Thelma') from **pairwise rows of t**' does not work
but 'estimate name, similarity to (name='Thelma') from **pairwise t**' does

I should make a ticket about that right?
Because the message error while entering 'estimate name, similarity to (name='Thelma') from **pairwise rows of t**' is not clear

**Comment by riastradh-probcomp** [comment]
Oops.  I forgot the syntax because I haven't used it in probably a year.

**Comment by BelhalK** [comment]
No worries.
The message error does not help neither.
We'll work on it

**Comment by riastradh-probcomp** [comment]
Hmm.  How could it be better?  I get:

    Syntax error near [of] after [estimate foo from pairwise rows]

BQL doesn't know that you meant 'rows' to be a keyword and not just the name of a generator/table.

**Comment by BelhalK** [comment]
Ok it makes sense.
Since **pairwise rows of t** would be the intuitive way to write it I thought about avoiding the pain of getting this message in the first place.
But it's true that the message is straight forward (meaning nothing should be after **pairwise** but the name of the generator)

**Comment by gregory-marton** [comment]
A potentially more helpful message would be "no such generator 'rows'", rather than dying at syntax further down.
A potentially better behavior would be to allow "ROWS OF" in that location.

**Comment by riastradh-probcomp** [comment]
The main reason I didn't put in `ROWS OF` is that the idea was for `COLUMNS OF t` to mean a table of the columns of t, whereas `t` already means a table of the rows of t, so `ROWS OF t` would be redundant.  Then -- in the future -- it would be nice to elaborate what you can do with `COLUMNS OF t`, e.g. SQL joins.
