### ISSUE TITLE
Unable to install bayeslite via source in virtualenv in ProbComp-2

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/bayeslite#399]
```
$ . /venv/fsaad-bdb/bin/activate
$ git clone https://github.com/probcomp/crosscat.git
$ pip install .
$ git clone https://github.com/probcomp/bayeslite-apsw.git
$ pip install .
$ git clone https://github.com/probcomp/bayeslite.git
$ git checkout 9e09a45
$ pip install .

[...]
/scratch/home/casarsa/venv/fsaad-bdb/local/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1448:1: warning: ‘int _import_array()’ defined but not used [-Wunused-function]

 _import_array(void)

 ^

error: command 'ccache' failed with exit status 1
```

**Comment by riastradh-probcomp** [comment]
Need a little more context here to know exactly what went wrong -- the message you quoted is actually a harmless warning, not the error that caused the C++ compiler to fail.  ('Harmless' in the sense that it doesn't indicate a problem for us in the code -- although it is harmful in the sense that it is confusing and leads us astray!)  The actual error message is probably either in the ellipsis or in the pip.log file.

Possible problem: bayeslite commit 9e09a45 requires crosscat 0.1.53 exactly (not any version newer than 0.1.53), but the current state of the crosscat Git repository contains >0.1.54, so `pip install .` will try to install crosscat 0.1.53 from pypi -- but the crosscat 0.1.53 distribution in pypi was broken (see https://github.com/probcomp/crosscat/issues/95), which might lead to the failure symptom you observed.

If you check out the v0.1.53 tag in crosscat first, that might help:

    $ . /venv/fsaad-bdb/bin/activate
    $ git clone https://github.com/probcomp/crosscat.git
    $ git checkout v0.1.53
    $ pip install .
    $ git clone https://github.com/probcomp/bayeslite-apsw.git
    $ pip install .
    $ git clone https://github.com/probcomp/bayeslite.git
    $ git checkout 9e09a45
    $ pip install .
