### ISSUE TITLE
Errors with plurals in queries

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/bayeslite#403]
```
q('''ESTIMATE CORRELATIONS FROM PAIRWISE COLUMNS OF %g''')
q('''ESTIMATE CORRELATION PVALUES FROM PAIRWISE COLUMNS OF %g''')
```

- will post the errors soon

**Comment by riastradh-probcomp** [comment]
Write `CORRELATION` and `CORRELATION PVALUE` -- the idea is that you're doing a singular thing, once for each row of input.

**Comment by leocasarsa** [comment]
Sure, my point being that users might commit the same mistakes and I don't see why they should be punished for it.

**Comment by fsaad** [comment]
I think that the singular `correlation` and `correlation pvlaue` is the correct choice, just like `dependence probability` versus `dependence probabilities` etc. Consider SQL, you say 'SELECT ABS(x)` for all rows in column `x`, versus the plural `ABSOLUTE VALUES(x)`. It might help to observe that the rows of the table `COLUMNS OF %g` contain two column names.
