### ISSUE TITLE
Error: issue with '()' in a BQL query

### ISSUE THREAD

**Issue by BelhalK** [probcomp/bayeslite#408]
It seems that when a variable has parenthesis in its name, the query crashes.
I've tried out with many satellites name.
'%' fix the issue but it could not be optimal sometimes

![capture d ecran 2016-05-09 a 16 09 07](https://cloud.githubusercontent.com/assets/15817944/15126544/7c91d2d0-1600-11e6-9319-eb2668bb716e.png)

**Comment by riastradh-probcomp** [comment]
Does it *crash* or does it simply return no results?  All I see from that image is no results.  If you replace `MaSat 1%` by `MaSat 1 (%`, does it still return no results?  What is the exact text -- US-ASCII code point by code point, or byte by byte -- of the satellite's name?

**Comment by gregory-marton** [comment]
The satellite name has two spaces between "MaSat 1" and "(Magyar".
