### ISSUE TITLE
Policy for a missing header

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#409]
I have a file `foo.csv` with the following 2 rows

```
, Name
0, bar
```

Using `.csv foo foo.csv` populates the table `foo` where the first column has the name `""`:

```
SELECT "" FROM foo LIMIT 1;
0
```

We should deal more gracefully with these situations, perhaps by 
- Populating missing header with a default value i.e. col0
- Tell the user to populate their headers

**Comment by riastradh-probcomp** [comment]
The `bayeslite.read_csv` module lets you specify whether to expect a header or not.

How would you like to tell the `.csv` command about that?

How do you distinguish a header from data?

**Comment by fsaad** [comment]
f3df7ac
