### ISSUE TITLE
Bayeslite / crosscat deadlock

### ISSUE THREAD

**Issue by alxempirical** [probcomp/bayeslite#421]
I have some data which reliably deadlocks bayeslite when using the crosscat multiprocessing engine on an AWS c4.8xlarge instance.

The data is all performance measurements I've done on satellites.bdb queries, so I should be able to share it here soon.  But worth recording here in the meantime:

```
ubuntu@c4:~$ for p in `ps -aef | grep python | awk '{ print $2 }'` ; do ( sudo strace -v -p $p & ) ; done                                                                                                                                                                     
Process 33090 attached
futex(0x7b81260, FUTEX_WAIT_PRIVATE, 0, NULLProcess 33074 attached
wait4(-1, Process 33100 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33101 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33099 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33102 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33104 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33103 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33106 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33107 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33105 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33110 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33108 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33111 attached
Process 33109 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLfutex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33113 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33115 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33112 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33114 attached
Process 33117 attached
Process 33119 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLfutex(0x7ff737172000, FUTEX_WAIT, 0, NULLfutex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33120 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33116 attached
read(6, Process 33125 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33121 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33127 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33124 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33123 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33128 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33122 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33126 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLubuntu@c4:~$ Process 33130 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33133 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33129 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33131 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33134 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLProcess 33132 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULLstrace: attach: ptrace(PTRACE_ATTACH, ...): No such process
Process 33324 attached
futex(0x7ff737172000, FUTEX_WAIT, 0, NULL^C
```

**Comment by riastradh-probcomp** [comment]
Sounds likely to be a bug in Python multiprocessing (which would not surprise me).  Otherwise neither bayeslite nor crosscat does anything interesting concerning threads and processes.

Can you attach gdb and get a stack trace when it's hung?

**Comment by alxempirical** [comment]
The problem goes away if I remove a column with high cardinality.  Deadlocking with a high-cardinality categorical column is apparently a known issue.  Is there an issue open on it?

**Comment by riastradh-probcomp** [comment]
When you said 'deadlock' I assumed you meant the system was making no progress because it was stuck in a bad lock state or something, hence my question about attaching gdb.

High-cardinality categorical columns tend to require a lot of memory -- possibly more than you have available on your system, which could easily grind the system to a swapping halt (but, though thrashing, it would still be making some progress).

The memory use of sparse categorical columns is bad.  Specifically, for m models with an average of v views each with an average of c categories per view and an average of n variables per view, each with an average of k distinct values, the space complexity is O(m v c n k).  (Yes, that's a product -- and yes, that's independent of the sparseness of the categorical values.)  I thought there was an open issue about it -- and certainly I've quoted that space complexity before in other issues -- but I can't find one specifically about this memory usage.

**Comment by alxempirical** [comment]
> When you said 'deadlock' I assumed you meant the system was making no progress because it was stuck in a bad lock state 

That is what I meant, and how I was interpreting the hanging FUTEX_WAIT calls.

I'll check whether the memory is blowing up with the broken schema when the current calculation is done.

**Comment by riastradh-probcomp** [comment]
OK, if it really is stuck doing nothing, can you attach gdb and get a stack trace?
