### ISSUE TITLE
add statistical type SCALE

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#433]

**Comment by fsaad** [comment]
Define SCALE please.

**Comment by fsaad** [comment]
Related #425

**Comment by riastradh-probcomp** [comment]
A scale is a positive, or perhaps nonnegative, real.  Maybe we should really have a statistical type for any half-open interval, and another one for any closed interval, but I expect variables supported on half-open intervals bounded below by zero to be a very common case.

**Comment by fsaad** [comment]
The README in gpmcc suggests a stattype called `IN-RANGE(a,b)` which we can achieve by scaling a beta, truncating a normal, etc.

**Comment by fsaad** [comment]
Fixed 7cc3a6b0d60c19e20cda580876d7d254026bee95, with SCALE as MAGNITUDE.
