### ISSUE TITLE
Update compiler.py to detect non-existent latent variable in a population

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#438]
If you try to simulate a latent variable directly FROM a population, a crash will happen somewhere in the metamodel code. The compiler should detect this case and report a nice error message.

**Comment by riastradh-probcomp** [comment]
Should be fixed in 8bd0de5f195e57fa89b21e719a74df99c6092780.  Need some more automatic tests.  See also #440.

**Comment by riastradh-probcomp** [comment]
Remaining work: write tests to exercise this.  Also make the compiler check bayesdb_has_variable first and report a BQLError in that case, since apparently I didn't do that everywhere (e.g., compile_pdf_joint).

**Comment by fsaad** [comment]
@riastradh-probcomp if you are happy https://github.com/probcomp/bayeslite/commit/312e32672d862f9853e40086105d3fc36326fded closes the bug.

**Comment by riastradh-probcomp** [comment]
Close enough.  We can make another issue for test coverage of error branches to get the stragglers.
