### ISSUE TITLE
eliminate core.bayesdb_generator_column_*

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#443]
These should be replaced by bayesdb_variable__, or at least replaced by bayesdb_generator_variable__.
- [ ] bayesdb_generator_column_name
- [ ] bayesdb_generator_column_names
- [ ] bayesdb_generator_column_number
- [ ] bayesdb_generator_column_numbers
- [ ] bayesdb_generator_column_stattype
- [ ] bayesdb_generator_has_column

**Comment by riastradh-probcomp** [comment]
...or this should all be replaced by populationdb, or this should be a step on the way to that.

**Comment by fsaad** [comment]
https://github.com/probcomp/bayeslite/commit/d2376c134942f40b3305cdf972be708e7404f25a
