### ISSUE TITLE
Implement INFER ... USING K SAMPLES

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#454]
As it stands a user can specify the number of samples for mutual information i.e.

`ESTIMATE MUTUAL INFORMATION OF a WITH b FROM foo USING 100 SAMPLES`.

We need a similar feature, for `INFER`, i.e.

`INFER a FROM foo USING 1000 SAMPLES`.

The logic already exists in `bqlfn` so all metamodels can already take `numsamples` as an argument, see here: https://github.com/probcomp/bayeslite/blob/master/src/bqlfn.py#L344-L345.

We just need to teach the grammar/compiler to take in the extra clause. This feature is essential, for us to avoid hacks such as [this one](https://github.com/probcomp/bayeslite/blob/20160624-riastradh-cgpm/src/metamodels/cgpm_metamodel.py#L331-L334).

**Comment by riastradh-probcomp** [comment]
Fixed in <https://github.com/probcomp/bayeslite/commit/9e2862343f4c0f2a38af9295bd7e35d180ad09d9>.
