### ISSUE TITLE
bayesdb-demo can't find bdbcontrib/examples

### ISSUE THREAD

**Issue by jdupl123** [probcomp/bayeslite#463]
as per http://probcomp.csail.mit.edu/bayesdb/install.html

i did

pip install bayeslite bdbcontrib

bayesdb-demo --destination ~/bayesdb

Did not find the bdbcontrib/examples directory in this distribution.

bayesdb-demo is in 

anaconda3/envs/py2/bin/bayesdb-demo
while bdcontrib/examples is in anaconda3/envs/py2/

is there a way to specify path for bayesdb-demo?

**Comment by gregory-marton** [comment]
Try `bayesdb-demo --source=anaconda3/envs/py2/bdbcontrib/examples`

**Comment by jdupl123** [comment]
Thanks that works. Potentially consider adding it to the error message?
