### ISSUE TITLE
Patch outdated/incorrect bayeslite terminology

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#467]
What is now called a `metamodel` -> `runtime`, and all associated methods (such as `bayesdb_metamodel`,`bayesdb_register_metamodel`, and so on) need to be updated. What is now called `generator` -> `metamodel`, and `generator_id` and the like will go to `metamodel_id`.

**Comment by riastradh-probcomp** [comment]
I'm not too keen on 'runtime' because it suggests it is only about implementation details of getting anything at all to run, when in fact it substantively determines the class of hypothesis spaces that one can express.  Sure, the two main ones, `crosscat` and `cgpm`, share a common default family of hypothesis spaces when no details are specified, namely crosscat, with different implementations, namely lovecat vs feralcat -- but that's not inherent, and it's not a priori clear to me that it *should* be inherent.  E.g., why a Chinese restaurant process instead of an Indian buffet process?

**Comment by fsaad** [comment]
> when in fact it substantively determines the class of hypothesis spaces that one can express. 

It is wrong to say that the runtime substantively determines class of hypothesis spaces that one can express. We have been using this notion loosely to make progress, but it breaks down quite quickly under inspection. The class of hypothesis spaces that one can express is not constrained by `cgpm`, it is determined by the contents of the meta-model schema. This notion will become more clear with time as we converge on the generality of `cgpm`, and agree that it is not restricted to either crosscat or univariate "foreign predictor" style cgpms that we have worked with so far.

For  consider the current MML program hosted on probcomp-1:
```
CREATE METAMODEL iris_g FOR iris_p USING cgpm(  
    LATENT flower_pc1 NUMERICAL,
    LATENT flower_pc2 NUMERICAL,

    MODEL sepal_length, sepal_width, petal_length, petal_width,
        flower_pc1, flower_pc2
    USING factor_analysis(L=2)
);
```
The hypothesis space induced by this MML program is unrelated to crosscat -- this space is parameterized by a set of 2 basis vectors in R^4, and each individual "hypothesis" is a pair of such basis vectors (unique up to signs). The "class" of hypothesis spaces is the set of all finite dimensional Euclidean spaces with L basis vectors. The IBP that you describe is treated in the same spirit as the factor analysis example.

Following this reasoning, in the long term (after we properly split bayeslite) we will eliminate the notion of what is now called metamodel/runtime. All MML programs and meta-modeling tactics are executed against a single implicit MML interpreter/runtime system (aka cgpm or a derivative), i.e.
```
CREATE METAMODEL foo FOR p(
   schema ...
)
```

> , and it's not a priori clear to me that it should be inherent

By default, the BayesDB MML interpreter uses CrossCat: A Fully Bayesian Nonparametric Method for Analyzing Heterogeneous, High Dimensional Data, to learn the joint distribution of all unmodeled variables in the population.  The fact that BayesDB uses crosscat as the default hypothesis space is an _inherent_ characteristic of the system, at least for the foreseeable future, and there are many reasons for this.

**Comment by fsaad** [comment]
https://github.com/probcomp/bayeslite/commit/f1a0c7e8d3dd8e29ed88371e73b8da8969cae9e6#diff-a166bdadbd0b273bc69a72070432406e

Supports GENERATOR and METAMODEL interchangeably.

**Comment by fsaad** [comment]
https://github.com/probcomp/bayeslite/commit/d2376c134942f40b3305cdf972be708e7404f25a
