### ISSUE TITLE
Quick search box in BQL doc returns nothing for important keywords

### ISSUE THREAD

**Issue by Schaechtle** [probcomp/bayeslite#471]
Trying the [quick-search box for the  BQL doc](http://probcomp.csail.mit.edu/bayesdb/doc/bql.html#) for the keywords _generator_ and _csv_ returns an empty page as result.

Ideally, it would have told me what queries are documented that contain those keywords.

**Comment by riastradh-probcomp** [comment]
It looks like the search function generated by sphinx is just completely broken.  I can't get any answers out of it.

**Comment by fsaad** [comment]
Should be fixed at http://probcomp.csail.mit.edu/bayesdb/doc/ by b2ca081f
