### ISSUE TITLE
Implement MML syntax for updating statistical types of population variables

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#476]
Mock up syntax
```
UPDATE POPULATION <population>
    SET STATTYPES FOR <columns> TO <stattype>,
    SET STATTYPES FOR <columns-prime> TO <stattype-prime>
```

The population should have no metamodel associated with it, otherwise the database will become inconsistent (or we would need to propagate the stattype change down to all metamodels defined for the population, which is a separate ticket).

The main idea for this change is allowing the user to easily modify the stattypes returned by `GUESS`.

**Comment by curlette** [comment]
Just as a side note, the user could also modify stattypes by first running `GUESS SCHEMA FOR <table>`, which will output a schema with the guessed stattypes, and then edit the schema manually.

**Comment by fsaad** [comment]
Nice addition.
