### ISSUE TITLE
Search box not working on website bayeslite documentation

### ISSUE THREAD

**Issue by versar** [probcomp/bayeslite#501]
Searching in the search box at http://probcomp.csail.mit.edu/bayesdb/doc/ seems to always come up blank with no results.

**Comment by fsaad** [comment]
Related/duplicate issue at #471. Not sure what is the latest status.

**Comment by fsaad** [comment]
Should be fixed at http://probcomp.csail.mit.edu/bayesdb/doc/ by b2ca081
