### ISSUE TITLE
Suggestion: Implement syntax for easily populating columns with values

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#519]
Derived from https://github.com/probcomp/bayeslite/issues/516

SQL let's you insert values into a column one value at a time
```
UPDATE <table> SET <column> = <value> WHERE <filter>
```

In BQL, we should implement the following convenience wrapper
```
UPDATE <table> SET <column> = (SELECT key, col FROM T) INNER JOIN USING  <key>
```
which does a bulk version of `UPDATE` from SQL.

**Comment by riastradh-probcomp** [comment]
What's wrong with just this?

    UPDATE <table> SET <column> = (SELECT t.col FROM t WHERE t.key = key)

What is the join accomplishing for you?

**Comment by fsaad** [comment]
@riastradh-probcomp I need a bulk operation which sets many values all in one-go.

The following code in `iventure`, using python for-loops might clarify the intention:

```
resids = %sql SELECT residual FROM gapminder_monitor_t;
for rowid, resid in enumerate(resids.values):
    %sql UPDATE gapminder_monitor_t \
        SET mortality_maternal_resid_log_linear = {resid[0]} WHERE rowid={rowid+1}
```

**Comment by riastradh-probcomp** [comment]
It's not exactly clear to me what you're trying to do with this query.

If the rowids of gapminder_monitor_t are contiguous and 1-based, then you can simplify this program a great deal:

    UPDATE gapminder_monitor_t
        SET mortality_maternal_resid_log_linear = resid;

But maybe you meant for the value to be some interesting function of the rowid indexed by some other table, in which case you can do something like:

    UPDATE gapminder_monitor_t
        SET mortality_maternal_resid_log_linear =
            (SELECT f(t.resid) FROM other_table AS t
                WHERE t.gapminder_monitor_id = rowid)

**Comment by fsaad** [comment]
@riastradh-probcomp here is what I am achieving in a single query

```
>> select * from f;
name | a | b
-----+---+---
joe  | 0 |
bob  | 1 |
qux  | 2 |
joe  | 3 |

>> select * from g;
name | b
-----+---
joe  | 4
bob  | 9

-- some single bql query
>> select * from f;
name | a | b
-----+---+---
joe  | 0 | 4
bob  | 1 | 9
qux  | 2 |
joe  | 3 | 4
```

**Comment by riastradh-probcomp** [comment]
UPDATE f
        SET b = (SELECT f.b FROM f WHERE f.name = name)

Does that not do what you want?

**Comment by fsaad** [comment]
@riastradh-probcomp your query did not work ... 

```
sqlite> select * from f;
name|a|b
joe|0|
bob|1|
qux|2|
joe|3|
sqlite> select * from g;
name|b
joe|4
bob|9
sqlite> update f set b = (select f.b from f where f.name = name);
sqlite> select * from f;
name|a|b
joe|0|
bob|1|
qux|2|
joe|3|
```

**Comment by fsaad** [comment]
@riastradh-probcomp I believe that in SQLITE, the `<value>` in 

`UPDATE <table> SET <column> = <value> WHERE <filter>`

seems scalar-valued, at least I don't know of any table-valued `<value>` which achieves the updates in my original example

**Comment by riastradh-probcomp** [comment]
I mistyped the other table name -- I meant to write `g` in two places where I wrote `f`.  Here's a full example:

    % sqlite3
    SQLite version 3.8.2 2013-12-06 14:53:30
    Enter ".help" for instructions
    Enter SQL statements terminated with a ";"
    sqlite> create table f(name, a, b);
    sqlite> create table g(name, b);
    sqlite> insert into f(name, a) values
       ...>   ('joe', 0),
       ...>   ('bob', 1),
       ...>   ('qux', 2),
       ...>   ('joe', 3);
    sqlite> insert into g(name, b) values
       ...>   ('joe', 4),
       ...>   ('bob', 9);
    sqlite> select * from f;
    joe|0|
    bob|1|
    qux|2|
    joe|3|
    sqlite> select * from g;
    joe|4
    bob|9
    sqlite> update f set b = (select g.b from g where g.name = f.name);
    sqlite> select * from f;
    joe|0|4
    bob|1|9
    qux|2|
    joe|3|4
    sqlite> 

You are right that the *&lt;value&gt;* is scalar-valued, but `UPDATE` modifies *every* matching row (which is every row, if there's no `WHERE`), evaluating the scalar-valued expression for each matching row.

**Comment by fsaad** [comment]
> You are right that the <value> is scalar-valued, but UPDATE modifies every matching row (which is every row, if there's no WHERE), evaluating the scalar-valued expression for each matching row.

Above was the key point, thanks!
