### ISSUE TITLE
change wording of WITH RESPECT TO in SIMILARITY

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#527]

**Comment by fsaad** [comment]
`IN THE CONTEXT OF`.

**Comment by fsaad** [comment]
@riastradh-probcomp the `IN` in `IN THE CONTEXT OF` is going to cause a conflict with SQL `IN`.

**Comment by fsaad** [comment]
@riastradh-probcomp one possibility is to kill the `WITHIN` as an alias for `BY` and use it for `WITHIN THE CONTEXT OF`, or user parenthesis...

**Comment by riastradh-probcomp** [comment]
IN doesn't cause a problem here.  (Not really keen on the verbiage 'IN THE CONTEXT OF'...)

**Comment by riastradh-probcomp** [comment]
I spoke too soon.  I ran check.sh in the wrong directory.

**Comment by fsaad** [comment]
`INSIDE THE CONTEXT OF`.

**Comment by fsaad** [comment]
ee57ab980eb20fbb471e6f3c3c35e21fa169e31c
