### ISSUE TITLE
allow statements in shell .python command

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#54]

**Comment by gregory-marton** [comment]
I would tend to do this kind of thing in a python program that uses bql, rather than in the shell. I think we're prioritizing notebooks for most interaction, so I recommend wontfix.

**Comment by riastradh-probcomp** [comment]
I added a `.pythexec` command in commit 1d423d7276b681cff211dd80ce6c5505cb5925d1.  If someone else wants to figure out how to mix expressions and statements, gopher it.
