### ISSUE TITLE
Revive USING MODEL in BQL

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#543]
```
ESTIMATE ... FROM <population> MODELED BY <metamodel> USING MODELS <modelnos>
SIMULATE ... FROM <population> MODELED BY <metamodel> USING MODELS <modelnos>
```
Related: https://github.com/probcomp/cgpm/issues/208

Will cause the test suite to catch fire since all method in `bqlfn.py` will admit an additional parameter and break all associated tests in `test_bql.py`.

**Comment by riastradh-probcomp** [comment]
What is the revision you are suggesting?

**Comment by fsaad** [comment]
Sorry "revive", not "revise", and I am referring to to cgpm_metamodel dropping all models.
https://github.com/probcomp/bayeslite/blob/master/src/metamodels/cgpm_metamodel.py#L275-L285

**Comment by fsaad** [comment]
And, this ticket was a duplicate (from a stale tab):
https://github.com/probcomp/bayeslite/issues/544

**Comment by fsaad** [comment]
> And, this ticket was a duplicate (from a stale tab): #544

#544 was another ticket for `DROP MODELS`. This ticket is indeed still outstanding.

Progress on this ticket in 20170624-fsaad-using-model.

**Comment by fsaad** [comment]
Design choice:

1. USING MODELS must have a MODELED BY <metamodel>.
`ESTIMATE ... FROM <pop> [MODELED BY <metamodel> [USING MODELS <modelnos>]]`

2. USING MODELS need not have a MODELED BY <metamodel>.
`ESTIMATE ... FROM <pop> [MODELED BY <metamodel>] [USING MODELS <modelnos>]`
If there is no `MODELED BY <metamodel>`
 - If there is just 1 metamodel in the population (the common case), use its modelnos .
 - If there are several metamodels for the population, try using modelnos for all: and crash if any do not have those modelnos.

**Comment by fsaad** [comment]
Branch is tested and ready for merge at
https://github.com/probcomp/bayeslite/compare/20170624-fsaad-using-model

Outstanding items are:
- Addressing the design choice from the previous comment;
- Deciding where to report a BQLError for invalid model indexes (currently throws IndexError or similar).

Separate tickets:
- Updating documentation to include modelnos where appropriate (separate ticket, since places like `ANALYZE`, `DROP MODELS` etc all accepts modelnos which are currently undocumented).

**Comment by fsaad** [comment]
https://github.com/probcomp/bayeslite/commit/a6056a7cc2ea77c5b6d818d46ae3c574a9fd5a88
