### ISSUE TITLE
Implement REGRESS

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#548]
```
REGRESS <target> GIVEN <*|vars|subexp> [USING <k> SAMPLES]
BY <population> [MODELED BY <metamodel>]
```
Returns a table with two columns -- the first column is the variable name (or category for a nominal stattype) and the second column is the regression coefficient.

**Comment by riastradh-probcomp** [comment]
Why a whole new kind of query instead of simply an expression composed within a query?

**Comment by fsaad** [comment]
`REGRESS` returns two columns, so its behavior is different than those functions which already exist in e.g. bqlfn or other BQL estimators, instead it behaves similarly to `GUESS SCHEMA FOR <table>`

**Comment by riastradh-probcomp** [comment]
Done in ebf0339cc557dc6a63902fbfe1ad7e01510fe9fa.
