### ISSUE TITLE
REGRESS tests should be integration-only

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#551]
- [x] (defer to another day) Consider adopting the `--integration` mechanism from cgpm.
- [x] (3ce2d94c2a8f262ca5b606c73d6d818158d4b152) Mark REGRESS tests as integration tests.
- [x] Add a bayeslite-master-ubuntu1604-integration job to jenkins.

**Comment by fsaad** [comment]
The `--integration` mechanism could be used to replace the existing `__ci_slow` convention.

We probably should explicitly mark `--integration` with a reason, for example `__ci_slow` versus `__ci_dependency`, since integration tests might be slow, or might require optional dependencies, etc.

**Comment by fsaad** [comment]
While addressing the issue of integration tests and dependencies, we should also address this pattern for skipping tests based on dependencies from [tests/test_loom#L33-L37](https://github.com/probcomp/bayeslite/blob/master/tests/test_loom.py):
```python
def loom_analyze(csv_filename):
    try:
        import loom
    except ImportError:
        pytest.skip('no loom')
        return

...

def test_loom_dha__ci_slow():
    loom_analyze(dha_csv)

def test_loom_satellites__ci_slow():
    loom_analyze(satellites_csv)
```

**Comment by riastradh-probcomp** [comment]
My idea with `--integration` was to mark that as the one for integration tests requiring a full suite of dependencies; we could separately have `--slow`, `--network`, &c., and maybe `--all` to run them all.
