### ISSUE TITLE
Install LOG as a sqlite function

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#561]

**Comment by riastradh-probcomp** [comment]
As in logarithm or as in logging?

I think once upon a time I felt bad about adding SQL functions not beginning with `bql_` or something, back when I thought of bayeslite as a composable extension on top of sqlite3 that you could combine with something else of the same class in the same sqlite3 database.  But that is probably no longer the case.  So feel free to add it to bqlfn.py.

**Comment by fsaad** [comment]
logarithm

**Comment by fsaad** [comment]
We could do a little meta-programming and install all functions in the python `math` standard library available to bql, which would be a pretty neat addition.

**Comment by fsaad** [comment]
https://github.com/probcomp/bayeslite/commit/f5ed22248e8bd5170ee5ed66a4eb830bff990267
