### ISSUE TITLE
Resolve extreme confusion with CREATE METAMODEL syntax

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#562]
Old and deprecated:
`CREATE METAMODEL <m> FOR <p> USING crosscat;`

These versions are equivalent, and the second version should be used only:
`CREATE METAMODEL <m> FOR <p> USING cgpm;`
`CREATE METAMODEL <m> FOR <p> WITH BASELINE crosscat;`

Actually, the full syntax would be
`CREATE METAMODEL <m> FOR <p> WITH BASELINE crosscat USING cgpm;`

**Comment by fsaad** [comment]
Also note that `ANALYSIS SCHEMA` is the preferred name to `METAMODEL`.

**Comment by curlette** [comment]
Not to mention `GENERATOR`. Should the plan be to somehow deprecate and remove `METAMODEL`, `GENERATOR` and `USING cgpm`?

**Comment by fsaad** [comment]
`GENERATOR/METAMODEL` is even more problematic because there is an internal notion of "generator" (which is now known externally as a metamodel), and an internal notion of a "metamodel" (which is now known as a "runtime", and is what comes after `CREATE METAMODEL <m> FOR <p> WITH BASELINE < USING <runtime>`).

Refactoring the bayeslite internals would therefore require the following:
- Rename bayeslite.generator -> bayeslite.metamodel to match BQL `METAMODEL`.
- Rename bayeslite.metamodel -> bayeslite.runtime to match BQL `USING <runtime>`

The risk with removing generator from the surface syntax is that it is one of the last traces for what generator means internally to bayeslite, and the bus load of that knowledge is 2.

`USING cgpm` should not be deprecated, there are genuine use cases for `USING <runtime>`. For example, a robust integration of Loom would likely happen by implementing it as a runtime rather than a CGPM which is accessed via cgpm lib (as the current `LOOM` integration does).

**Comment by fsaad** [comment]
https://github.com/probcomp/bayeslite/commit/d2376c134942f40b3305cdf972be708e7404f25a
