### ISSUE TITLE
Decide what to do about the scipy dependency

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#567]
Status quo is that asking for correlation p-value will attempt to import scipy, which is not declared as a dependency.  We should either
- declare a dependency on scipy, or
- make the error message nicer

This does not affect the probcomp stack overmuch, because other stack packages depend on scipy (Venturecxx, iventure via seaborn, and cgpm)

**Comment by fsaad** [comment]
Declared dependency.
