### ISSUE TITLE
Loom has slow performance in `_store_kind_partition` after estimating CrossCat model

### ISSUE THREAD

**Issue by versar** [probcomp/bayeslite#584]
After estimating the CrossCat partition, the implementation of loom in bayeslite stores the CrossCat views, and for each view the row partitions, into a BQL table. This is implemented in a nested loop (over models, over views, and over rows) leading to a high number of SQL insertions.

https://github.com/probcomp/bayeslite/blob/fdf7f2fb0621c9696887745e58a71bb95392142b/src/metamodels/loom_metamodel.py#L436-L444

Some possibilities for addressing this issue include:
- constructing a Pandas dataframe and using df.to_sql to store the dataframe into the .bdb object
- construct a big string for one bulk SQL INSERT
- add query types that exist in bayeslite but not Loom to the Loom query server

**Comment by fsaad** [comment]
Also consider wrapping inserts in a transaction.

**Comment by versar** [comment]
Fixed by @fsaad using a bulk INSERT operation.
