### ISSUE TITLE
fix (old?) link to website

### ISSUE THREAD

**Issue by afeld** [probcomp/bayeslite#630]
The URL at the top of this repository and in https://github.com/probcomp/bayesdb goes to a 404 page:

http://probcomp.csail.mit.edu/bayesdb

Seems like the URL changed to http://probcomp.csail.mit.edu/software/bayesdb/? Might be good to fix those links, and/or put in a redirect.

Thanks!

**Comment by fsaad** [comment]
The links have been updated, thank you!

**Comment by afeld** [comment]
Thanks!
