### ISSUE TITLE
switch from Python sqlite3 module to apsw

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#92]
http://rogerbinns.github.io/apsw/

apsw supports:

- sqlite3_backup API, so we can save in-memory databases to disk and take reliable snapshots of databases on disk
- virtual tables, so we can obviate the need to create a large intermediate table up-front for SIMULATE
- less obnoxious automagic DB-API transaction nonsense to work around
- anything else in the sqlite3 API we care about

But it also means a nontrivial external dependency.

**Comment by axch** [comment]
Would ease #238 by providing corresponding modes for the underlying sqlite database, which sqlite3 apparently does not.

**Comment by riastradh-probcomp** [comment]
Someone^TM should just do this.  I started on the 20150210-riastradh-apsw branch <https://github.com/probcomp/bayeslite/tree/20150210-riastradh-apsw>, but at this point it would probably be better to start afresh using that branch as inspiration than to whittle that branch into shape.

**Comment by riastradh-probcomp** [comment]
20151119-riastradh-apsw https://github.com/probcomp/bayeslite/pull/320

**Comment by riastradh-probcomp** [comment]
Done in c492cf326663599cc58adfa81d34d6d757004fd8.  Depend on >=0.1.4a20151203 to get this.
